// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Collection Page documents */
interface CollectionPageDocumentData {
    /**
     * Slice Zone field in *Collection Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<CollectionPageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *Collection Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: collection_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *Collection Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *Collection Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: collection_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Collection Page → Slice Zone*
 *
 */
type CollectionPageDocumentDataSlicesSlice = never;
/**
 * Collection Page document from Prismic
 *
 * - **API ID**: `collection_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CollectionPageDocumentData>,
    'collection_page',
    Lang
>;
/** Content for Custom Page documents */
interface CustomPageDocumentData {
    /**
     * Title field in *Custom Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Description field in *Custom Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * Slice Zone field in *Custom Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<CustomPageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *Custom Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: custom_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *Custom Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *Custom Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: custom_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
    /**
     * Keywords field in *Custom Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismic.KeyTextField;
}
/**
 * Slice for *Custom Page → Slice Zone*
 *
 */
type CustomPageDocumentDataSlicesSlice =
    | CarouselSlice
    | CollectionSlice
    | ImageGridSlice
    | TextBlockSlice
    | CollapsibleTextSlice
    | VendorsSlice
    | IconGridSlice;
/**
 * Custom Page document from Prismic
 *
 * - **API ID**: `custom_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CustomPageDocumentData>,
    'custom_page',
    Lang
>;
/** Content for Legacy Footer documents */
interface FooterDocumentData {
    /**
     * Address field in *Legacy Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    address: prismic.RichTextField;
    /**
     * Show Language Selector field in *Legacy Footer*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: footer.show_language_selector
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    show_language_selector: prismic.BooleanField;
    /**
     * Show Currency Selector field in *Legacy Footer*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: footer.show_currency_selector
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    show_currency_selector: prismic.BooleanField;
    /**
     * Slice zone field in *Legacy Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismic.SliceZone<FooterDocumentDataBodySlice>;
}
/**
 * Primary content in Legacy Footer → Slice zone → `block` → Primary
 *
 */
interface FooterDocumentDataBodyBlockSlicePrimary {
    /**
     * Title field in *Legacy Footer → Slice zone → `block` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
}
/**
 * Item in Legacy Footer → Slice zone → `block` → Items
 *
 */
export interface FooterDocumentDataBodyBlockSliceItem {
    /**
     * Title field in *Legacy Footer → Slice zone → `block` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Handle field in *Legacy Footer → Slice zone → `block` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.items[].handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
}
export type FooterDocumentDataBodyBlockSlice = prismic.Slice<
    'block',
    Simplify<FooterDocumentDataBodyBlockSlicePrimary>,
    Simplify<FooterDocumentDataBodyBlockSliceItem>
>;
/**
 * Slice for *Legacy Footer → Slice zone*
 *
 */
type FooterDocumentDataBodySlice = FooterDocumentDataBodyBlockSlice;
/**
 * Legacy Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    'footer',
    Lang
>;
/** Content for Global Header documents */
interface GlobalHeaderDocumentData {
    /**
     * Announcements field in *Global Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: global_header.announcements[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    announcements: prismic.GroupField<Simplify<GlobalHeaderDocumentDataAnnouncementsItem>>;
}
/**
 * Item in Global Header → Announcements
 *
 */
export interface GlobalHeaderDocumentDataAnnouncementsItem {
    /**
     * Location field in *Global Header → Announcements*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: above
     * - **API ID Path**: global_header.announcements[].location
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    location: prismic.SelectField<'above' | 'bellow', 'filled'>;
    /**
     * Background Color field in *Global Header → Announcements*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: secondary
     * - **API ID Path**: global_header.announcements[].background_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    background_color: prismic.SelectField<'secondary' | 'primary', 'filled'>;
    /**
     * Content field in *Global Header → Announcements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Free shipping on orders above $75
     * - **API ID Path**: global_header.announcements[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismic.RichTextField;
}
/**
 * Global Header document from Prismic
 *
 * - **API ID**: `global_header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalHeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalHeaderDocumentData>,
    'global_header',
    Lang
>;
/** Content for Legacy Header documents */
interface HeadDocumentData {
    /**
     * Announcements field in *Legacy Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: head.announcements[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    announcements: prismic.GroupField<Simplify<HeadDocumentDataAnnouncementsItem>>;
}
/**
 * Item in Legacy Header → Announcements
 *
 */
export interface HeadDocumentDataAnnouncementsItem {
    /**
     * Location field in *Legacy Header → Announcements*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: above
     * - **API ID Path**: head.announcements[].location
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    location: prismic.SelectField<'above' | 'bellow', 'filled'>;
    /**
     * Background Color field in *Legacy Header → Announcements*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: secondary
     * - **API ID Path**: head.announcements[].background_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    background_color: prismic.SelectField<'secondary' | 'primary', 'filled'>;
    /**
     * Content field in *Legacy Header → Announcements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Free shipping on orders above $75
     * - **API ID Path**: head.announcements[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismic.RichTextField;
}
/**
 * Legacy Header document from Prismic
 *
 * - **API ID**: `head`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeadDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<HeadDocumentData>,
    'head',
    Lang
>;
/** Content for Legacy Navigation documents */
interface NavigationDocumentData {
    /**
     * Slice zone field in *Legacy Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismic.SliceZone<NavigationDocumentDataBodySlice>;
}
/**
 * Primary content in Legacy Navigation → Slice zone → `link` → Primary
 *
 */
interface NavigationDocumentDataBodyLinkSlicePrimary {
    /**
     * Title field in *Legacy Navigation → Slice zone → `link` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Handle field in *Legacy Navigation → Slice zone → `link` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.primary.handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
}
/**
 * Item in Legacy Navigation → Slice zone → `link` → Items
 *
 */
export interface NavigationDocumentDataBodyLinkSliceItem {
    /**
     * Title field in *Legacy Navigation → Slice zone → `link` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Description field in *Legacy Navigation → Slice zone → `link` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * Handle field in *Legacy Navigation → Slice zone → `link` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.items[].handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
}
export type NavigationDocumentDataBodyLinkSlice = prismic.Slice<
    'link',
    Simplify<NavigationDocumentDataBodyLinkSlicePrimary>,
    Simplify<NavigationDocumentDataBodyLinkSliceItem>
>;
/**
 * Slice for *Legacy Navigation → Slice zone*
 *
 */
type NavigationDocumentDataBodySlice = NavigationDocumentDataBodyLinkSlice;
/**
 * Legacy Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
>;
/** Content for Legacy Page documents */
interface PageDocumentData {
    /**
     * title field in *Legacy Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Page Title
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Description field in *Legacy Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Page Description
     * - **API ID Path**: page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * Keywords field in *Legacy Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Page Keywords
     * - **API ID Path**: page.keywords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    keywords: prismic.KeyTextField;
    /**
     * Slice zone field in *Legacy Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismic.SliceZone<PageDocumentDataBodySlice>;
}
/**
 * Primary content in Legacy Page → Slice zone → `carousel` → Primary
 *
 */
interface PageDocumentDataBodyCarouselSlicePrimary {
    /**
     * Delay field in *Legacy Page → Slice zone → `carousel` → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 3000
     * - **API ID Path**: page.body[].carousel.primary.delay
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    delay: prismic.NumberField;
}
/**
 * Item in Legacy Page → Slice zone → `carousel` → Items
 *
 */
export interface PageDocumentDataBodyCarouselSliceItem {
    /**
     * Image field in *Legacy Page → Slice zone → `carousel` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].carousel.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * href field in *Legacy Page → Slice zone → `carousel` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].carousel.items[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismic.KeyTextField;
}
export type PageDocumentDataBodyCarouselSlice = prismic.Slice<
    'carousel',
    Simplify<PageDocumentDataBodyCarouselSlicePrimary>,
    Simplify<PageDocumentDataBodyCarouselSliceItem>
>;
/**
 * Primary content in Legacy Page → Slice zone → `collection` → Primary
 *
 */
interface PageDocumentDataBodyCollectionSlicePrimary {
    /**
     * handle field in *Legacy Page → Slice zone → `collection` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Collection handle
     * - **API ID Path**: page.body[].collection.primary.handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
    /**
     * Limit field in *Legacy Page → Slice zone → `collection` → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: max amount of products to show
     * - **API ID Path**: page.body[].collection.primary.limit
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    limit: prismic.NumberField;
    /**
     * direction field in *Legacy Page → Slice zone → `collection` → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: vertical
     * - **API ID Path**: page.body[].collection.primary.layout
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    layout: prismic.SelectField<'vertical' | 'horizontal', 'filled'>;
    /**
     * Hide title field in *Legacy Page → Slice zone → `collection` → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page.body[].collection.primary.hide_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    hide_title: prismic.BooleanField;
}
export type PageDocumentDataBodyCollectionSlice = prismic.Slice<
    'collection',
    Simplify<PageDocumentDataBodyCollectionSlicePrimary>,
    never
>;
export type PageDocumentDataBodyShopblockSlice = prismic.Slice<
    'shopblock',
    Record<string, never>,
    never
>;
export type PageDocumentDataBodyVendorsSlice = prismic.Slice<
    'vendors',
    Record<string, never>,
    never
>;
/**
 * Item in Legacy Page → Slice zone → `textblock` → Items
 *
 */
export interface PageDocumentDataBodyTextblockSliceItem {
    /**
     * Image field in *Legacy Page → Slice zone → `textblock` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].textblock.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Text field in *Legacy Page → Slice zone → `textblock` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].textblock.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismic.RichTextField;
}
export type PageDocumentDataBodyTextblockSlice = prismic.Slice<
    'textblock',
    Record<string, never>,
    Simplify<PageDocumentDataBodyTextblockSliceItem>
>;
/**
 * Primary content in Legacy Page → Slice zone → `notification` → Primary
 *
 */
interface PageDocumentDataBodyNotificationSlicePrimary {
    /**
     * Content field in *Legacy Page → Slice zone → `notification` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].notification.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    content: prismic.KeyTextField;
}
export type PageDocumentDataBodyNotificationSlice = prismic.Slice<
    'notification',
    Simplify<PageDocumentDataBodyNotificationSlicePrimary>,
    never
>;
/**
 * Primary content in Legacy Page → Slice zone → `icon_grid` → Primary
 *
 */
interface PageDocumentDataBodyIconGridSlicePrimary {
    /**
     * Secondary field in *Legacy Page → Slice zone → `icon_grid` → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page.body[].icon_grid.primary.secondary
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    secondary: prismic.BooleanField;
}
/**
 * Item in Legacy Page → Slice zone → `icon_grid` → Items
 *
 */
export interface PageDocumentDataBodyIconGridSliceItem {
    /**
     * Icon field in *Legacy Page → Slice zone → `icon_grid` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].icon_grid.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismic.ImageField<never>;
    /**
     * Title field in *Legacy Page → Slice zone → `icon_grid` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: text
     * - **API ID Path**: page.body[].icon_grid.items[].title1
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title1: prismic.TitleField;
}
export type PageDocumentDataBodyIconGridSlice = prismic.Slice<
    'icon_grid',
    Simplify<PageDocumentDataBodyIconGridSlicePrimary>,
    Simplify<PageDocumentDataBodyIconGridSliceItem>
>;
/**
 * Primary content in Legacy Page → Slice zone → `collapse` → Primary
 *
 */
interface PageDocumentDataBodyCollapseSlicePrimary {
    /**
     * Title field in *Legacy Page → Slice zone → `collapse` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].collapse.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Body field in *Legacy Page → Slice zone → `collapse` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].collapse.primary.body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismic.RichTextField;
}
export type PageDocumentDataBodyCollapseSlice = prismic.Slice<
    'collapse',
    Simplify<PageDocumentDataBodyCollapseSlicePrimary>,
    never
>;
/**
 * Item in Legacy Page → Slice zone → `imagelinks` → Items
 *
 */
export interface PageDocumentDataBodyImagelinksSliceItem {
    /**
     * Image field in *Legacy Page → Slice zone → `imagelinks` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].imagelinks.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Title field in *Legacy Page → Slice zone → `imagelinks` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].imagelinks.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Handle field in *Legacy Page → Slice zone → `imagelinks` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].imagelinks.items[].handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
}
export type PageDocumentDataBodyImagelinksSlice = prismic.Slice<
    'imagelinks',
    Record<string, never>,
    Simplify<PageDocumentDataBodyImagelinksSliceItem>
>;
/**
 * Slice for *Legacy Page → Slice zone*
 *
 */
type PageDocumentDataBodySlice =
    | PageDocumentDataBodyCarouselSlice
    | PageDocumentDataBodyCollectionSlice
    | PageDocumentDataBodyShopblockSlice
    | PageDocumentDataBodyVendorsSlice
    | PageDocumentDataBodyTextblockSlice
    | PageDocumentDataBodyNotificationSlice
    | PageDocumentDataBodyIconGridSlice
    | PageDocumentDataBodyCollapseSlice
    | PageDocumentDataBodyImagelinksSlice;
/**
 * Legacy Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<PageDocumentData>,
    'page',
    Lang
>;
/** Content for Product Page documents */
interface ProductPageDocumentData {
    /**
     * Slice Zone field in *Product Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<ProductPageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *Product Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: product_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *Product Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *Product Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: product_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Product Page → Slice Zone*
 *
 */
type ProductPageDocumentDataSlicesSlice = never;
/**
 * Product Page document from Prismic
 *
 * - **API ID**: `product_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<ProductPageDocumentData>,
    'product_page',
    Lang
>;
/** Content for Store documents */
interface StoreDocumentData {
    /**
     * Store name field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.store_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    store_name: prismic.KeyTextField;
    /**
     * Logo field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    logo: prismic.KeyTextField;
    /**
     * Favicon field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.favicon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    favicon: prismic.KeyTextField;
    /**
     * Primary field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: store.primary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    primary: prismic.ColorField;
    /**
     * Secondary field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: store.secondary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    secondary: prismic.ColorField;
    /**
     * Primary Text Color field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: store.primary_text_color
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    primary_text_color: prismic.ColorField;
    /**
     * Corner radius field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.border_radius
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    border_radius: prismic.KeyTextField;
    /**
     * Currencies field in *Store*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: store.currencies[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    currencies: prismic.GroupField<Simplify<StoreDocumentDataCurrenciesItem>>;
    /**
     * Social field in *Store*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: store.social[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social: prismic.GroupField<Simplify<StoreDocumentDataSocialItem>>;
}
/**
 * Item in Store → Currencies
 *
 */
export interface StoreDocumentDataCurrenciesItem {
    /**
     * currency field in *Store → Currencies*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.currencies[].currency
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    currency: prismic.KeyTextField;
}
/**
 * Item in Store → Social
 *
 */
export interface StoreDocumentDataSocialItem {
    /**
     * Name field in *Store → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.social[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismic.KeyTextField;
    /**
     * Link field in *Store → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.social[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismic.KeyTextField;
    /**
     * Handle field in *Store → Social*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.social[].handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
}
/**
 * Store document from Prismic
 *
 * - **API ID**: `store`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoreDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<StoreDocumentData>,
    'store',
    Lang
>;
export type AllDocumentTypes =
    | CollectionPageDocument
    | CustomPageDocument
    | FooterDocument
    | GlobalHeaderDocument
    | HeadDocument
    | NavigationDocument
    | PageDocument
    | ProductPageDocument
    | StoreDocument;
/**
 * Primary content in Carousel → Primary
 *
 */
interface CarouselSliceDefaultPrimary {
    /**
     * Delay field in *Carousel → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 3000
     * - **API ID Path**: carousel.primary.delay
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    delay: prismic.KeyTextField;
}
/**
 * Item in Carousel → Items
 *
 */
export interface CarouselSliceDefaultItem {
    /**
     * Image field in *Carousel → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Mobile Image field in *Carousel → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mobile_image: prismic.ImageField<never>;
    /**
     * href field in *Carousel → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.items[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismic.KeyTextField;
}
/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CarouselSliceDefaultPrimary>,
    Simplify<CarouselSliceDefaultItem>
>;
/**
 * Slice variation for *Carousel*
 *
 */
type CarouselSliceVariation = CarouselSliceDefault;
/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: `Carousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarouselSlice = prismic.SharedSlice<'carousel', CarouselSliceVariation>;
/**
 * Primary content in CollapsibleText → Primary
 *
 */
interface CollapsibleTextSliceDefaultPrimary {
    /**
     * Title field in *CollapsibleText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Text field in *CollapsibleText → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismic.RichTextField;
}
/**
 * Default variation for CollapsibleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollapsibleTextSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CollapsibleTextSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *CollapsibleText*
 *
 */
type CollapsibleTextSliceVariation = CollapsibleTextSliceDefault;
/**
 * CollapsibleText Shared Slice
 *
 * - **API ID**: `collapsible_text`
 * - **Description**: `CollapsibleText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollapsibleTextSlice = prismic.SharedSlice<
    'collapsible_text',
    CollapsibleTextSliceVariation
>;
/**
 * Primary content in Collection → Primary
 *
 */
interface CollectionSliceDefaultPrimary {
    /**
     * Handle field in *Collection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.primary.handle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    handle: prismic.KeyTextField;
    /**
     * Item Limit field in *Collection → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 16
     * - **API ID Path**: collection.primary.limit
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    limit: prismic.NumberField;
    /**
     * Direction field in *Collection → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: horizontal
     * - **API ID Path**: collection.primary.direction
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    direction: prismic.SelectField<'horizontal' | 'vertical', 'filled'>;
    /**
     * Hide Title field in *Collection → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: collection.primary.hide_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    hide_title: prismic.BooleanField;
}
/**
 * Default variation for Collection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CollectionSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *Collection*
 *
 */
type CollectionSliceVariation = CollectionSliceDefault;
/**
 * Collection Shared Slice
 *
 * - **API ID**: `collection`
 * - **Description**: `Collection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSlice = prismic.SharedSlice<'collection', CollectionSliceVariation>;
/**
 * Item in IconGrid → Items
 *
 */
export interface IconGridSliceDefaultItem {
    /**
     * Icon field in *IconGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_grid.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismic.ImageField<never>;
    /**
     * Title field in *IconGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
}
/**
 * Default variation for IconGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<IconGridSliceDefaultItem>
>;
/**
 * Slice variation for *IconGrid*
 *
 */
type IconGridSliceVariation = IconGridSliceDefault;
/**
 * IconGrid Shared Slice
 *
 * - **API ID**: `icon_grid`
 * - **Description**: `IconGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconGridSlice = prismic.SharedSlice<'icon_grid', IconGridSliceVariation>;
/**
 * Item in ImageGrid → Items
 *
 */
export interface ImageGridSliceDefaultItem {
    /**
     * Image field in *ImageGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Title field in *ImageGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * href field in *ImageGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismic.KeyTextField;
}
/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ImageGridSliceDefaultItem>
>;
/**
 * Slice variation for *ImageGrid*
 *
 */
type ImageGridSliceVariation = ImageGridSliceDefault;
/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: `ImageGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageGridSlice = prismic.SharedSlice<'image_grid', ImageGridSliceVariation>;
/**
 * Item in TextBlock → Items
 *
 */
export interface TextBlockSliceDefaultItem {
    /**
     * Image field in *TextBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Text field in *TextBlock → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismic.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<TextBlockSliceDefaultItem>
>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismic.SharedSlice<'text_block', TextBlockSliceVariation>;
/**
 * Default variation for Vendors Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VendorsSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    never
>;
/**
 * Slice variation for *Vendors*
 *
 */
type VendorsSliceVariation = VendorsSliceDefault;
/**
 * Vendors Shared Slice
 *
 * - **API ID**: `vendors`
 * - **Description**: `Vendors`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VendorsSlice = prismic.SharedSlice<'vendors', VendorsSliceVariation>;
declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type {
            CollectionPageDocumentData,
            CollectionPageDocumentDataSlicesSlice,
            CollectionPageDocument,
            CustomPageDocumentData,
            CustomPageDocumentDataSlicesSlice,
            CustomPageDocument,
            FooterDocumentData,
            FooterDocumentDataBodyBlockSlicePrimary,
            FooterDocumentDataBodyBlockSliceItem,
            FooterDocumentDataBodyBlockSlice,
            FooterDocumentDataBodySlice,
            FooterDocument,
            GlobalHeaderDocumentData,
            GlobalHeaderDocumentDataAnnouncementsItem,
            GlobalHeaderDocument,
            HeadDocumentData,
            HeadDocumentDataAnnouncementsItem,
            HeadDocument,
            NavigationDocumentData,
            NavigationDocumentDataBodyLinkSlicePrimary,
            NavigationDocumentDataBodyLinkSliceItem,
            NavigationDocumentDataBodyLinkSlice,
            NavigationDocumentDataBodySlice,
            NavigationDocument,
            PageDocumentData,
            PageDocumentDataBodyCarouselSlicePrimary,
            PageDocumentDataBodyCarouselSliceItem,
            PageDocumentDataBodyCarouselSlice,
            PageDocumentDataBodyCollectionSlicePrimary,
            PageDocumentDataBodyCollectionSlice,
            PageDocumentDataBodyShopblockSlice,
            PageDocumentDataBodyVendorsSlice,
            PageDocumentDataBodyTextblockSliceItem,
            PageDocumentDataBodyTextblockSlice,
            PageDocumentDataBodyNotificationSlicePrimary,
            PageDocumentDataBodyNotificationSlice,
            PageDocumentDataBodyIconGridSlicePrimary,
            PageDocumentDataBodyIconGridSliceItem,
            PageDocumentDataBodyIconGridSlice,
            PageDocumentDataBodyCollapseSlicePrimary,
            PageDocumentDataBodyCollapseSlice,
            PageDocumentDataBodyImagelinksSliceItem,
            PageDocumentDataBodyImagelinksSlice,
            PageDocumentDataBodySlice,
            PageDocument,
            ProductPageDocumentData,
            ProductPageDocumentDataSlicesSlice,
            ProductPageDocument,
            StoreDocumentData,
            StoreDocumentDataCurrenciesItem,
            StoreDocumentDataSocialItem,
            StoreDocument,
            AllDocumentTypes,
            CarouselSliceDefaultPrimary,
            CarouselSliceDefaultItem,
            CarouselSliceDefault,
            CarouselSliceVariation,
            CarouselSlice,
            CollapsibleTextSliceDefaultPrimary,
            CollapsibleTextSliceDefault,
            CollapsibleTextSliceVariation,
            CollapsibleTextSlice,
            CollectionSliceDefaultPrimary,
            CollectionSliceDefault,
            CollectionSliceVariation,
            CollectionSlice,
            IconGridSliceDefaultItem,
            IconGridSliceDefault,
            IconGridSliceVariation,
            IconGridSlice,
            ImageGridSliceDefaultItem,
            ImageGridSliceDefault,
            ImageGridSliceVariation,
            ImageGridSlice,
            TextBlockSliceDefaultItem,
            TextBlockSliceDefault,
            TextBlockSliceVariation,
            TextBlockSlice,
            VendorsSliceDefault,
            VendorsSliceVariation,
            VendorsSlice
        };
    }
}
