import type { IconManifestEntry } from './types';

const HEADER = `// generated by scripts/generate.ts — do not edit by hand.\n`;

export type EmitIconArgs = {
    entry: IconManifestEntry;
    viewBox: string;
    innerJsx: string;
};

export function emitIconComponent({ entry, viewBox, innerJsx }: EmitIconArgs): string {
    return `${HEADER}import { IconShell, type PaymentIconProps } from '../../shell';

export default function ${entry.componentName}(props: PaymentIconProps) {
    return (
        <IconShell viewBox="${viewBox}" title="${entry.title}" {...props}>
            ${innerJsx}
        </IconShell>
    );
}
`;
}

export function emitIconsMapModule(entries: readonly IconManifestEntry[]): string {
    const body = entries.map((e) => `    '${e.slug}': () => import('./icons/${e.slug}.js'),`).join('\n');
    return `${HEADER}import type { ComponentType } from 'react';
import type { PaymentIconProps } from '../shell';

export const ICONS: Record<string, () => Promise<{ default: ComponentType<PaymentIconProps> }>> = {
${body}
};
`;
}

export function emitAliasesModule(entries: readonly IconManifestEntry[]): string {
    const lines: string[] = [];
    for (const e of entries) for (const a of e.aliases) lines.push(`    '${a}': '${e.slug}',`);
    const body = lines.length > 0 ? `\n${lines.join('\n')}\n` : '';
    return `${HEADER}export const ALIASES: Record<string, string> = {${body}};
`;
}

export function emitManifestModule(entries: readonly IconManifestEntry[]): string {
    const body = entries
        .map((e) => {
            const aliasArray = `[${e.aliases.map((a) => `'${a}'`).join(', ')}]`;
            return `    { slug: '${e.slug}', componentName: '${e.componentName}', title: '${e.title.replace(/'/g, "\\'")}', aliases: ${aliasArray} },`;
        })
        .join('\n');
    return `${HEADER}import type { IconManifestEntry } from '../../scripts/types';

export const manifest: readonly IconManifestEntry[] = [
${body}
] as const;
`;
}

export function emitNamesModule(entries: readonly IconManifestEntry[]): string {
    const slugUnion = entries.map((e) => `'${e.slug}'`).join(' | ') || 'never';
    const aliases = entries.flatMap((e) => e.aliases);
    const aliasUnion = aliases.length > 0 ? aliases.map((a) => `'${a}'`).join(' | ') : 'never';
    return `${HEADER}export type PaymentIconName = ${slugUnion};
export type PaymentIconAlias = ${aliasUnion};
export type PaymentIconNameOrAlias = PaymentIconName | PaymentIconAlias;
`;
}

export function emitIndexModule(entries: readonly IconManifestEntry[]): string {
    const body = entries.map((e) => `export { default as ${e.componentName} } from './icons/${e.slug}';`).join('\n');
    return `${HEADER}${body}
`;
}
