// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
    alert: dynamic(() => import('./Alert')),
    banner: dynamic(() => import('./Banner')),
    carousel: dynamic(() => import('./Carousel')),
    collapsible_text: dynamic(() => import('./CollapsibleText')),
    collection: dynamic(() => import('./Collection')),
    icon_grid: dynamic(() => import('./IconGrid')),
    image_grid: dynamic(() => import('./ImageGrid')),
    text_block: dynamic(() => import('./Overview')),
    vendors: dynamic(() => import('./Vendors'))
};
