// AUTO-GENERATED by apps/docs/scripts/generate-page-map.mjs - do not edit.
/* eslint-disable */

export type PageMapEntry = {
    slug: string;
    type: 'app' | 'package';
    pages: string[];
    sourceWorkspacePath: string;
};

export const pageMap: PageMapEntry[] = [
    { slug: 'admin', type: 'app', pages: ['overview'], sourceWorkspacePath: 'apps/admin' },
    {
        slug: 'landing',
        type: 'app',
        pages: [
            'errors/API_METHOD_NOT_ALLOWED',
            'errors/API_UNKNOWN_ERROR',
            'errors/API_UNKNOWN_LOCALE',
            'errors/GENERIC_TODO',
            'errors/NOT_FOUND',
            'errors/UNREACHABLE',
            'overview',
        ],
        sourceWorkspacePath: 'apps/landing',
    },
    {
        slug: 'storefront',
        type: 'app',
        pages: ['data-fetching', 'locales', 'overview', 'routing', 'webhooks'],
        sourceWorkspacePath: 'apps/storefront',
    },
    {
        slug: 'cms',
        type: 'package',
        pages: [
            'access',
            'api',
            'blocks',
            'blocks/render',
            'cache',
            'collections',
            'config',
            'editor',
            'editor-adding-a-collection',
            'editor-manifests',
            'editor-overview',
            'editor/manifests',
            'editor/ui',
            'fields',
            'index',
            'overview',
            'plugins',
            'server-functions',
            'shop-sync',
            'test-utils',
            'types',
            'ui',
        ],
        sourceWorkspacePath: 'packages/cms',
    },
    {
        slug: 'db',
        type: 'package',
        pages: ['index', 'models', 'overview', 'services'],
        sourceWorkspacePath: 'packages/db',
    },
    { slug: 'errors', type: 'package', pages: ['index', 'overview'], sourceWorkspacePath: 'packages/errors' },
    {
        slug: 'marketing-common',
        type: 'package',
        pages: ['index', 'overview'],
        sourceWorkspacePath: 'packages/marketing-common',
    },
    {
        slug: 'shopify-graphql',
        type: 'package',
        pages: ['index', 'overview'],
        sourceWorkspacePath: 'packages/shopify-graphql',
    },
    {
        slug: 'shopify-html',
        type: 'package',
        pages: ['index', 'overview'],
        sourceWorkspacePath: 'packages/shopify-html',
    },
    {
        slug: 'tagtree/core',
        type: 'package',
        pages: ['contract-tests', 'index', 'overview'],
        sourceWorkspacePath: 'packages/tagtree/core',
    },
    {
        slug: 'tagtree/next',
        type: 'package',
        pages: ['index', 'overview'],
        sourceWorkspacePath: 'packages/tagtree/next',
    },
    {
        slug: 'tagtree/payload',
        type: 'package',
        pages: ['index', 'overview'],
        sourceWorkspacePath: 'packages/tagtree/payload',
    },
    {
        slug: 'tagtree/shopify',
        type: 'package',
        pages: ['index', 'overview'],
        sourceWorkspacePath: 'packages/tagtree/shopify',
    },
];
