#!/usr/bin/env tsx
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_APP = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(DOCS_APP, '../..');
const OUT_FILE = path.join(DOCS_APP, 'lib/source-meta.generated.ts');

type Redirect = { source: string; destination: string; permanent: true };

const STATIC_REDIRECTS: Redirect[] = [
    { source: '/docs/getting-started/', destination: '/docs/get-started/quickstart/', permanent: true },
    { source: '/docs/architecture/', destination: '/docs/get-started/architecture/', permanent: true },
    { source: '/docs/contributing/', destination: '/docs/operations/contributing/', permanent: true },
    { source: '/docs/deployment/', destination: '/docs/operations/deployment/', permanent: true },
    { source: '/docs/conventions/', destination: '/docs/operations/conventions/', permanent: true },
    { source: '/docs/typescript-project-structure/', destination: '/docs/operations/typescript-project-structure/', permanent: true },
];

/**
 * Emit `lib/source-meta.generated.ts` with a typed `redirects` array consumed
 * by `next.config.mjs` and a statically-typed `GeneratedRedirect` type. Static
 * redirects cover historical doc URLs; per-workspace catch-alls cover the
 * generated `(generated)/<slug>` URL shape that existed before the nav refactor.
 *
 * @param options - Optional quiet flag to suppress console output.
 * @returns Count of redirects written.
 */
export function main({ quiet = false }: { quiet?: boolean } = {}): { redirects: number } {
    const all: Redirect[] = [...STATIC_REDIRECTS];

    // Per-workspace catch-all: /docs/(generated)/<slug>/<rest>? → /docs/packages/<slug>/<rest>?
    const workspaceSlugs = discoverWorkspaceSlugs();
    for (const slug of workspaceSlugs) {
        all.push({
            source: `/docs/(generated)/${slug}/:rest*`,
            destination: `/docs/packages/${slug}/:rest*`,
            permanent: true,
        });
    }

    const body = [
        '// AUTO-GENERATED by apps/docs/scripts/build-source-meta.ts — do not edit.',
        '/* eslint-disable */',
        '',
        'export type GeneratedRedirect = { source: string; destination: string; permanent: true };',
        '',
        `export const redirects: GeneratedRedirect[] = ${JSON.stringify(all, null, 4)};`,
        '',
    ].join('\n');

    fs.writeFileSync(OUT_FILE, body);
    if (!quiet) console.info(`[build-source-meta] wrote ${all.length} redirects`);
    return { redirects: all.length };
}

/**
 * Walk `apps/` and `packages/` to discover every workspace that has a
 * `package.json`. Returns a flat list of slug strings suitable for use in
 * Next.js redirect patterns. Skips hidden dirs, `node_modules`, `dist`, and
 * other tooling directories.
 *
 * @returns Array of workspace path slugs relative to the repo root.
 */
function discoverWorkspaceSlugs(): string[] {
    const out: string[] = [];
    for (const parent of ['apps', 'packages'] as const) {
        const root = path.join(REPO_ROOT, parent);
        if (!fs.existsSync(root)) continue;
        walk(root, [], out);
    }
    return out;
}

/**
 * Recursively collect workspace slugs. A directory is a workspace when it
 * contains `package.json` directly; otherwise we recurse into it.
 *
 * @param dir - Current directory to inspect.
 * @param segments - Accumulated path segments from the repo-root anchor.
 * @param out - Accumulator for discovered slugs.
 */
function walk(dir: string, segments: string[], out: string[]): void {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        if (
            !e.isDirectory() ||
            e.name.startsWith('.') ||
            ['node_modules', 'dist', 'build', '.next', '.turbo', 'src', 'docs'].includes(e.name)
        )
            continue;
        const full = path.join(dir, e.name);
        if (fs.existsSync(path.join(full, 'package.json'))) {
            out.push([...segments, e.name].join('/'));
        } else {
            walk(full, [...segments, e.name], out);
        }
    }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main();
}
