#!/usr/bin/env tsx
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_APP = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(DOCS_APP, '../..');
const GENERATED_ROOT = path.join(DOCS_APP, 'app/docs/(generated)');
const TYPEDOC_OUT = path.join(DOCS_APP, '.typedoc-out');
const PAGE_MAP_OUT = path.join(DOCS_APP, 'lib/page-map.generated.ts');

const SKIP_DIRS = new Set(['node_modules', 'dist', 'build', '.turbo', '.next', 'coverage', 'docs', 'src', 'api']);

type WorkspaceType = 'app' | 'package';

type Workspace = {
    slug: string;
    type: WorkspaceType;
    rootPath: string;
};

type PageMapEntry = {
    slug: string;
    type: WorkspaceType;
    pages: string[];
    sourceWorkspacePath: string;
};

type ExportsValue = string | string[] | { [condition: string]: ExportsValue } | null;

function discoverWorkspaces(): Workspace[] {
    const out: Workspace[] = [];
    for (const parent of ['apps', 'packages']) {
        const root = path.join(REPO_ROOT, parent);
        if (!fs.existsSync(root)) continue;
        for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
            if (!entry.isDirectory()) continue;
            if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) continue;
            walk(path.join(root, entry.name), parent, [entry.name], out);
        }
    }
    return out;
}

function walk(dir: string, parent: string, segments: string[], out: Workspace[]): void {
    if (fs.existsSync(path.join(dir, 'docs')) && fs.existsSync(path.join(dir, 'package.json'))) {
        out.push({ slug: segments.join('/'), type: parent === 'apps' ? 'app' : 'package', rootPath: dir });
        return;
    }
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (!entry.isDirectory()) continue;
        if (SKIP_DIRS.has(entry.name) || entry.name.startsWith('.')) continue;
        walk(path.join(dir, entry.name), parent, [...segments, entry.name], out);
    }
}

function readSubpaths(rootPath: string): string[] {
    const pkgPath = path.join(rootPath, 'package.json');
    if (!fs.existsSync(pkgPath)) return [];
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { exports?: ExportsValue };
    if (!pkg.exports || typeof pkg.exports === 'string') return ['.'];
    return Object.keys(pkg.exports);
}

function subpathToRoutePath(subpath: string): string {
    if (subpath === '.') return 'index';
    return subpath.replace(/^\.\//, '');
}

function subpathJsonExists(slug: string, subpath: string): boolean {
    const file = path.join(TYPEDOC_OUT, slug, `${subpathToRoutePath(subpath)}.json`);
    return fs.existsSync(file);
}

function hasMirroredFile(slug: string, routePath: string): boolean {
    const file = path.join(GENERATED_ROOT, slug, routePath, 'page.mdx');
    return fs.existsSync(file);
}

function synthesizeStub(slug: string, subpath: string): void {
    const route = subpathToRoutePath(subpath);
    const file = path.join(GENERATED_ROOT, slug, route, 'page.mdx');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const displayName = subpath === '.' ? slug : `${slug}/${route}`;
    const content = `---
title: ${subpath === '.' ? 'Overview' : route}
---

# ${displayName}

import { ApiReference } from '@/components/api/api-reference';

<ApiReference subpath="${slug}/${route}" />
`;
    fs.writeFileSync(file, content);
}

function listMirroredPages(slug: string): string[] {
    const root = path.join(GENERATED_ROOT, slug);
    if (!fs.existsSync(root)) return [];
    const pages: string[] = [];
    function visit(dir: string, segments: string[]): void {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            const full = path.join(dir, entry.name);
            if (entry.isFile() && entry.name === 'page.mdx') {
                pages.push(segments.join('/') || 'index');
            } else if (entry.isDirectory()) {
                visit(full, [...segments, entry.name]);
            }
        }
    }
    visit(root, []);
    return pages;
}

function writeMetaJson(slug: string, pages: string[]): void {
    const meta: Record<string, string> = {};
    for (const p of pages.sort()) {
        const segments = p.split('/');
        const top = segments[0];
        if (!top) continue;
        if (!meta[top]) {
            meta[top] = top === 'index' ? 'Overview' : top;
        }
    }
    const file = path.join(GENERATED_ROOT, slug, '_meta.json');
    if (fs.existsSync(path.dirname(file))) {
        fs.writeFileSync(file, JSON.stringify(meta, null, 2));
    }
}

function emitPageMapTs(entries: PageMapEntry[]): void {
    const lines = [
        '// AUTO-GENERATED by apps/docs/scripts/generate-page-map.ts - do not edit.',
        '/* eslint-disable */',
        '',
        'export type PageMapEntry = {',
        '    slug: string;',
        '    type: "app" | "package";',
        '    pages: string[];',
        '    sourceWorkspacePath: string;',
        '};',
        '',
        'export const pageMap: PageMapEntry[] = [',
    ];
    for (const e of entries) {
        lines.push(
            `    { slug: ${JSON.stringify(e.slug)}, type: ${JSON.stringify(e.type)}, pages: ${JSON.stringify(e.pages)}, sourceWorkspacePath: ${JSON.stringify(e.sourceWorkspacePath)} },`,
        );
    }
    lines.push('];');
    lines.push('');
    fs.writeFileSync(PAGE_MAP_OUT, lines.join('\n'));
    // No biome format pass: the output file is gitignored (see apps/docs/.gitignore)
    // and biome's ignore rules reject it anyway. The hand-written formatter above
    // produces consistent output across regenerations.
}

export function main({ quiet = false }: { quiet?: boolean } = {}): { workspaces: number; synthesized: number } {
    const workspaces = discoverWorkspaces();
    let synthesized = 0;

    for (const ws of workspaces) {
        // Synthesize stub pages for subpaths that have TypeDoc JSON but no mirrored MDX.
        const subpaths = readSubpaths(ws.rootPath);
        for (const sp of subpaths) {
            if (!subpathJsonExists(ws.slug, sp)) continue;
            const route = subpathToRoutePath(sp);
            if (!hasMirroredFile(ws.slug, route)) {
                synthesizeStub(ws.slug, sp);
                synthesized++;
            }
        }
    }

    const entries: PageMapEntry[] = workspaces.map((ws) => ({
        slug: ws.slug,
        type: ws.type,
        pages: listMirroredPages(ws.slug),
        sourceWorkspacePath: path.relative(REPO_ROOT, ws.rootPath),
    }));

    for (const e of entries) {
        writeMetaJson(e.slug, e.pages);
    }

    emitPageMapTs(entries);

    if (!quiet) {
        console.info(
            `[generate-page-map] processed ${workspaces.length} workspace(s); synthesized ${synthesized} stub page(s)`,
        );
    }
    return { workspaces: workspaces.length, synthesized };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main();
}
