/**
 * Payload admin root layout. Required by `@payloadcms/next/views` — without it,
 * the ConfigProvider context never mounts and any client component that calls
 * `useConfig()` crashes with "Cannot destructure property 'config' of … as it
 * is undefined".
 *
 * Re-exports the official RootLayout from `@payloadcms/next/layouts`, passing
 * our wired config and an empty importMap (regenerated by `payload generate:importmap`
 * once we have custom admin components).
 */

import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts';
import type { ServerFunctionClient } from 'payload';
import React from 'react';
import config from '../../payload.config';
import { importMap } from './importMap';

type Args = { children: React.ReactNode };

const serverFunction: ServerFunctionClient = async function (args) {
    'use server';
    return handleServerFunctions({
        ...args,
        config,
        importMap,
    });
};

const Layout = ({ children }: Args) => (
    <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
        {children}
    </RootLayout>
);

export default Layout;
