/**
 * Payload admin root layout. Required by `@payloadcms/next/views` — without it,
 * the ConfigProvider context never mounts and any client component that calls
 * `useConfig()` crashes with "Cannot destructure property 'config' of … as it
 * is undefined".
 *
 * Re-exports the official RootLayout from `@payloadcms/next/layouts`. The
 * importMap is auto-generated by Payload in dev (and at build time via
 * `payload generate:importmap`) to `./cms/importMap.js` — note the `cms`
 * segment matches our `routes.admin: '/cms'` setting.
 */

import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts';
import type { ServerFunctionClient } from 'payload';
import type React from 'react';
import config from '../../payload.config';
import './custom.scss';
import { importMap } from './cms/importMap';

// `RootLayout` reads cookies/headers via `initReq` (auth, locale, theme).
// Force the entire (payload) layout segment dynamic so the layout shell
// itself can't accidentally end up in a cached context — both `page.tsx`
// and the layout need this; a dynamic page inside a cached layout still
// trips DYNAMIC_SERVER_USAGE when the layout reads headers.
export const dynamic = 'force-dynamic';
export const revalidate = 0;

type Args = { children: React.ReactNode };

const serverFunction: ServerFunctionClient = async function (args) {
    'use server';
    return handleServerFunctions({
        ...args,
        config,
        importMap,
    });
};

const Layout = ({ children }: Args) => (
    <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
        {children}
    </RootLayout>
);

export default Layout;
