// Code generated by Slice Machine. DO NOT EDIT.

import Alert from './Alert';
import Banner from './Banner';
import CollapsibleText from './CollapsibleText';
import Collection from './Collection';
import Columns from './Columns';
import ContentBlock from './ContentBlock';
import IconGrid from './IconGrid';
import ImageGrid from './ImageGrid';
import Overview from './Overview';
import Title from './Title';
import Vendors from './Vendors';

export const components = {
    alert: Alert,
    banner: Banner,
    collapsible_text: CollapsibleText,
    collection: Collection,
    columns: Columns,
    content_block: ContentBlock,
    icon_grid: IconGrid,
    image_grid: ImageGrid,
    text_block: Overview,
    title: Title,
    vendors: Vendors
};
