import 'server-only';

import { MissingConvexBridgeError } from '@nordcom/commerce-errors';
import { revalidatePath } from 'next/cache';
import { notFound } from 'next/navigation';

import { parseFormPayload } from './form-payload';
import type { CollectionEditorManifest, EditorAccess } from './manifest';
import { refreshEditorPaths } from './revalidate';
import type { EditorConvexBridge, EditorDocumentTarget, EditorRuntime } from './runtime';

export type { EditorConvexBridge, EditorDocumentTarget } from './runtime';

/**
 * The out-of-band `FormData` key carrying the optimistic base version a draft save branched from
 * (G4FIX-01). The edit page's bound action stamps it server-side from the document read that seeded
 * the form, so it never round-trips through (or collides with) the `_payload` field blob.
 */
export const CMS_BASE_VERSION_FIELD = '_cms_base_version';

/**
 * Seven server-action methods generated per collection by `pnpm cms:gen`.
 * Each method is a plain async function that must be re-exported from a
 * `'use server'` module before being passed across an RSC boundary.
 *
 * @example
 * // In a generated 'use server' module:
 * export const { saveDraft, publish, create, delete: deleteDoc, bulkDelete, bulkPublish, restoreVersion } =
 *   createCollectionEditorActions(pagesEditor, editorRuntime);
 */
export type EditorActions = {
    saveDraft: (domain: string | null, id: string, formData: FormData, locale: string) => Promise<void>;
    publish: (domain: string | null, id: string, formData: FormData, locale: string) => Promise<void>;
    create: (domain: string | null, formData: FormData, locale: string) => Promise<{ id: string }>;
    delete: (domain: string | null, id: string) => Promise<void>;
    bulkDelete: (domain: string | null, ids: string[]) => Promise<void>;
    bulkPublish: (domain: string | null, ids: string[]) => Promise<void>;
    restoreVersion: (domain: string | null, id: string, versionId: string) => Promise<void>;
};

/**
 * Maps the editor route's `id` segment onto the bridge's document target using the manifest's
 * tenant kind and key field: singleton kinds carry no target (the tenant's one row IS the target,
 * resolved server-side), keyField-routed collections address by content key, and everything else
 * addresses by document id. Shared by the action factory below and the shell pages' bridge reads
 * (`getDocument`), so the read and write paths can never address differently.
 *
 * @param manifest - The collection's editor manifest (tenant kind + optional `routes.keyField`).
 * @param id - The URL id segment — a document id, a key value, or `''` for singletons.
 * @returns The bridge target for the save-shaped and read calls.
 */
export const documentTargetFor = (manifest: CollectionEditorManifest, id: string): EditorDocumentTarget => {
    if (manifest.tenant.kind === 'tenant-singleton' || manifest.tenant.kind === 'singleton-by-domain') {
        return {};
    }
    const keyField = manifest.routes.keyField ?? 'id';
    return keyField === 'id' ? { documentId: id } : { keyField, keyValue: id };
};

/**
 * Factory that builds the seven Convex-backed server-action methods for a manifest.
 *
 * Methods returned here are plain async functions — they MUST be re-exported from a `'use server'`
 * top-level module before being passed across an RSC boundary. `pnpm cms:gen` generates those
 * wrappers; do not call this factory directly inside a component module.
 *
 * Every method runs the manifest's route-level access gate first (`notFound()` on denial — the
 * defense-in-depth UX layer), then posts through the runtime's {@link EditorConvexBridge}, where
 * Convex's `cms/actions.ts` re-enforces access from the server-trusted identity. The form payload
 * is forwarded as parsed; key scrubbing is no longer a server concern here because the Convex side
 * pins the tenant from `ctx` — a smuggled `tenant`/`shopId` key in `data` is inert content.
 *
 * @param manifest - Editor manifest describing the collection and its access rules.
 * @param runtime - Per-app runtime bundle; its optional `convex` property is the Convex transport.
 * @returns An {@link EditorActions} object with all seven server-action methods bound to the manifest.
 *
 * @example
 * // In a 'use server' module generated by pnpm cms:gen:
 * export const { saveDraft, publish } = createCollectionEditorActions(pagesEditor, editorRuntime);
 */
export const createCollectionEditorActions = (
    manifest: CollectionEditorManifest,
    runtime: EditorRuntime,
): EditorActions => {
    /**
     * Returns the wired Convex transport, failing loud when the runtime was built without one —
     * a misconfigured app must surface immediately rather than silently dropping writes.
     *
     * @returns The runtime's {@link EditorConvexBridge}.
     * @throws {MissingConvexBridgeError} When the runtime carries no `convex` transport.
     */
    const bridge = (): EditorConvexBridge => {
        if (!runtime.convex) throw new MissingConvexBridgeError(manifest.collection);
        return runtime.convex;
    };

    /**
     * Runs a manifest access gate against the resolved auth context, `notFound()`-ing on denial
     * or when the gate is undeclared (e.g. a collection without `create`/`delete`). Route-level
     * defense in depth — the authoritative enforcement lives in Convex's `cms/actions.ts`.
     *
     * @param domain - Tenant domain, or `null` on cross-tenant routes.
     * @param gate - The manifest predicate for the operation, or `undefined` when unsupported.
     * @throws Next.js `notFound()` when the gate is missing or denies.
     */
    const assertAccess = async (domain: string | null, gate: EditorAccess | undefined): Promise<void> => {
        if (!gate) notFound();
        const ctx = await runtime.getCtx(domain);
        if (!(await gate(runtime.toAccessCtx(ctx, domain)))) notFound();
    };

    return {
        async saveDraft(domain, id, formData, locale) {
            await assertAccess(domain, manifest.access.update);
            const data = parseFormPayload(formData);
            // The optimistic base rides OUTSIDE `_payload` (set by the edit page's bound action,
            // never by form state) so `parseFormPayload`'s field scrubbing can't confuse it with
            // content. It names the version the editor branched from; the Convex side uses it to
            // flag a draft whose base a publish superseded (G4FIX-01) while merging it forward.
            const base = formData.get(CMS_BASE_VERSION_FIELD);
            // ZERO revalidation on the draft path — by contract. A draft autosave landing a
            // `revalidatePath` on the edit URL re-seeds `<Form>`'s `initialState` mid-keystroke,
            // and the Convex draft save schedules no storefront revalidation either (BRIDGE-05
            // arms only on the published transition).
            await bridge().saveDraft({
                collection: manifest.collection,
                data,
                locale,
                ...(typeof base === 'string' && base.length > 0 ? { baseVersionId: base } : {}),
                ...documentTargetFor(manifest, id),
            });
        },
        async publish(domain, id, formData, locale) {
            await assertAccess(domain, manifest.access.update);
            const data = parseFormPayload(formData);
            const { documentId } = await bridge().publish({
                collection: manifest.collection,
                data,
                locale,
                ...documentTargetFor(manifest, id),
            });
            // Storefront caches bust via the Convex publish hook; this only refreshes the admin's
            // own manifest-declared paths (list pages, edit views) for the operator.
            refreshEditorPaths({ manifest, domain, doc: { id: documentId }, status: 'published', revalidatePath });
        },
        async create(domain, formData, locale) {
            await assertAccess(domain, manifest.access.create);
            const data = parseFormPayload(formData);
            const { documentId } = await bridge().create({ collection: manifest.collection, data, locale });
            refreshEditorPaths({ manifest, domain, doc: { id: documentId }, status: 'draft', revalidatePath });
            return { id: documentId };
        },
        async delete(domain, id) {
            await assertAccess(domain, manifest.access.delete);
            await bridge().deleteDocument({ documentId: id });
            refreshEditorPaths({ manifest, domain, doc: { id }, status: 'published', revalidatePath });
        },
        async bulkDelete(domain, ids) {
            await assertAccess(domain, manifest.access.delete);
            await bridge().bulkDelete({ documentIds: ids });
            refreshEditorPaths({ manifest, domain, doc: { ids }, status: 'published', revalidatePath });
        },
        async bulkPublish(domain, ids) {
            await assertAccess(domain, manifest.access.update);
            await bridge().bulkPublish({ documentIds: ids });
            refreshEditorPaths({ manifest, domain, doc: { ids }, status: 'published', revalidatePath });
        },
        async restoreVersion(domain, id, versionId) {
            await assertAccess(domain, manifest.access.update);
            await bridge().restoreVersion({ versionId });
            refreshEditorPaths({ manifest, domain, doc: { id }, status: 'draft', revalidatePath });
        },
    };
};
