import 'server-only';

import { UnknownCollectionSlugError } from '@nordcom/commerce-errors';
import { revalidatePath } from 'next/cache';
import { notFound } from 'next/navigation';
import type { CollectionSlug } from 'payload';

import { parseFormPayload, pickByFieldNames } from './form-payload';
import type { CollectionEditorManifest } from './manifest';
import { revalidateForManifest, tenantWhere } from './revalidate';
import type { EditorRuntime } from './runtime';

/**
 * Seven server-action methods generated per collection by `pnpm cms:gen`.
 * Each method is a plain async function that must be re-exported from a
 * `'use server'` module before being passed across an RSC boundary.
 *
 * @example
 * // In a generated 'use server' module:
 * export const { saveDraft, publish, create, delete: deleteDoc, bulkDelete, bulkPublish, restoreVersion } =
 *   createCollectionEditorActions(pagesEditor, editorRuntime);
 */
export type EditorActions = {
    saveDraft: (domain: string | null, id: string, formData: FormData, locale: string) => Promise<void>;
    publish: (domain: string | null, id: string, formData: FormData, locale: string) => Promise<void>;
    create: (domain: string | null, formData: FormData, locale: string) => Promise<{ id: string }>;
    delete: (domain: string | null, id: string) => Promise<void>;
    bulkDelete: (domain: string | null, ids: string[]) => Promise<void>;
    bulkPublish: (domain: string | null, ids: string[]) => Promise<void>;
    restoreVersion: (domain: string | null, id: string, versionId: string) => Promise<void>;
};

/**
 * Factory that builds the seven server-action methods for a manifest.
 *
 * Methods returned here are plain async functions — they MUST be re-exported
 * from a `'use server'` top-level module before being passed across an RSC
 * boundary. `pnpm cms:gen` generates those wrappers; do not call this factory
 * directly inside a component module.
 *
 * @param manifest - Editor manifest describing the collection and its access rules.
 * @param runtime - Per-app runtime bundle providing `getCtx`, `buildFormState`, etc.
 * @returns An {@link EditorActions} object with all seven server-action methods bound to the manifest.
 *
 * @example
 * // In a 'use server' module generated by pnpm cms:gen:
 * export const { saveDraft, publish } = createCollectionEditorActions(pagesEditor, editorRuntime);
 */
export const createCollectionEditorActions = <T extends CollectionSlug>(
    manifest: CollectionEditorManifest<T>,
    runtime: EditorRuntime,
): EditorActions => {
    /**
     * Returns whether a collection has `versions.drafts` enabled.
     *
     * @param collection - Partial collection config subset containing `versions`.
     * @returns `true` when the collection supports draft saves.
     */
    const hasDrafts = (collection: { versions?: unknown }): boolean => {
        const v = collection.versions as { drafts?: unknown } | undefined;
        return v !== undefined && v.drafts !== undefined && v.drafts !== false;
    };

    /**
     * Finds the doc identified by `id` within the tenant scope and either
     * updates it or creates it. Applies the draft/publish status patch and
     * calls `revalidatePath` only for published writes.
     *
     * @param domain - Tenant domain, or `null` on cross-tenant routes.
     * @param id - Document id or keyField value used for the lookup.
     * @param formData - Raw `FormData` from the `<Form>` submit event.
     * @param status - Whether to write as `'draft'` or `'published'`.
     * @param locale - BCP-47 locale code for localized field round-tripping.
     */
    const upsert = async (
        domain: string | null,
        id: string,
        formData: FormData,
        status: 'draft' | 'published',
        locale: string,
    ): Promise<void> => {
        const ctx = await runtime.getCtx(domain);
        if (!(await manifest.access.update(runtime.toAccessCtx(ctx, domain)))) notFound();

        const collection = ctx.payload.config.collections.find((c) => c.slug === manifest.collection);
        if (!collection) {
            throw new UnknownCollectionSlugError(manifest.collection);
        }

        const raw = parseFormPayload(formData);
        const allowed = pickByFieldNames(raw, collection.fields);
        const where = tenantWhere(manifest, ctx.tenant, id);

        // Pass `locale` to Payload on every read+write so localized fields
        // round-trip through the same locale the editor is currently viewing.
        // Without it, Payload falls back to its configured `defaultLocale`
        // (en-US) and silently writes German text into the English bucket.
        const { docs } = await ctx.payload.find({
            collection: manifest.collection as never,
            where,
            limit: 1,
            locale: locale as never,
            user: ctx.user as never,
            overrideAccess: false,
            draft: hasDrafts(collection),
        });

        const drafts = hasDrafts(collection);
        const statusPatch = drafts ? { _status: status } : {};
        // Payload's `draft: true` option skips required-field validation so
        // partially-filled docs (e.g. a freshly-added block whose required
        // `Title` is still empty) can be autosaved. Without it, every
        // autosave tick throws `ValidationError` and the new block becomes
        // impossible to edit.
        const draftFlag = drafts && status === 'draft' ? { draft: true as const } : {};
        const existing = docs[0];

        let doc: unknown;
        if (existing) {
            doc = await ctx.payload.update({
                collection: manifest.collection as never,
                id: (existing as { id: string }).id,
                data: { ...allowed, ...statusPatch } as never,
                locale: locale as never,
                user: ctx.user as never,
                overrideAccess: false,
                ...draftFlag,
            });
        } else {
            const tenantPatch =
                (manifest.tenant.kind === 'scoped' || manifest.tenant.kind === 'tenant-singleton') && ctx.tenant
                    ? { tenant: ctx.tenant.id }
                    : {};
            doc = await ctx.payload.create({
                collection: manifest.collection as never,
                data: { ...allowed, ...tenantPatch, ...statusPatch } as never,
                locale: locale as never,
                user: ctx.user as never,
                overrideAccess: false,
                ...draftFlag,
            });
        }

        // Skip path revalidation on draft autosaves. Tenant-singleton manifests
        // declare their `revalidate` path as the admin's own edit URL, so a
        // 2-second autosave loop causes Next.js to revalidate the page the
        // user is editing — `<Form>`'s `initialState` effect then dispatches
        // REPLACE_STATE and clobbers every in-flight keystroke. Storefront
        // caches are already invalidated by the collection's `afterChange`
        // hook (`buildRevalidateHooks` → `revalidateTag`), so the only thing
        // we lose by skipping here is admin LIST-page freshness — which the
        // user sees on next navigation, not while editing.
        if (status === 'published') {
            revalidateForManifest({ manifest, domain, doc, status, revalidatePath });
        }
    };

    return {
        async saveDraft(domain, id, formData, locale) {
            await upsert(domain, id, formData, 'draft', locale);
        },
        async publish(domain, id, formData, locale) {
            await upsert(domain, id, formData, 'published', locale);
        },
        async create(domain, formData, locale) {
            const ctx = await runtime.getCtx(domain);
            const accessCtx = runtime.toAccessCtx(ctx, domain);
            if (!manifest.access.create) notFound();
            if (!(await manifest.access.create(accessCtx))) notFound();

            const collection = ctx.payload.config.collections.find((c) => c.slug === manifest.collection);
            if (!collection) throw new UnknownCollectionSlugError(manifest.collection);

            const raw = parseFormPayload(formData);
            const allowed = pickByFieldNames(raw, collection.fields);
            const tenantPatch =
                (manifest.tenant.kind === 'scoped' || manifest.tenant.kind === 'tenant-singleton') && ctx.tenant
                    ? { tenant: ctx.tenant.id }
                    : {};
            const drafts = hasDrafts(collection);
            const statusPatch = drafts ? { _status: 'draft' as const } : {};
            // See upsert(): `draft: true` skips required-field validation so a
            // brand-new doc with empty required fields (or freshly-added
            // blocks) can be autosaved before the user fills them in.
            const draftFlag = drafts ? { draft: true as const } : {};

            const created = (await ctx.payload.create({
                collection: manifest.collection as never,
                data: { ...allowed, ...tenantPatch, ...statusPatch } as never,
                locale: locale as never,
                user: ctx.user as never,
                overrideAccess: false,
                ...draftFlag,
            })) as { id: string };

            revalidateForManifest({ manifest, domain, doc: created, status: 'draft', revalidatePath });
            return { id: String(created.id) };
        },
        async delete(domain, id) {
            const ctx = await runtime.getCtx(domain);
            if (!manifest.access.delete) notFound();
            if (!(await manifest.access.delete(runtime.toAccessCtx(ctx, domain)))) notFound();

            await ctx.payload.delete({
                collection: manifest.collection as never,
                id,
                user: ctx.user as never,
                overrideAccess: false,
            });

            revalidateForManifest({ manifest, domain, doc: { id }, status: 'published', revalidatePath });
        },
        async bulkDelete(domain, ids) {
            const ctx = await runtime.getCtx(domain);
            if (!manifest.access.delete) notFound();
            if (!(await manifest.access.delete(runtime.toAccessCtx(ctx, domain)))) notFound();

            for (const id of ids) {
                await ctx.payload.delete({
                    collection: manifest.collection as never,
                    id,
                    user: ctx.user as never,
                    overrideAccess: false,
                });
            }
            revalidateForManifest({ manifest, domain, doc: { ids }, status: 'published', revalidatePath });
        },
        async bulkPublish(domain, ids) {
            const ctx = await runtime.getCtx(domain);
            if (!(await manifest.access.update(runtime.toAccessCtx(ctx, domain)))) notFound();

            for (const id of ids) {
                await ctx.payload.update({
                    collection: manifest.collection as never,
                    id,
                    data: { _status: 'published' } as never,
                    user: ctx.user as never,
                    overrideAccess: false,
                });
            }
            revalidateForManifest({ manifest, domain, doc: { ids }, status: 'published', revalidatePath });
        },
        async restoreVersion(domain, id, versionId) {
            const ctx = await runtime.getCtx(domain);
            if (!(await manifest.access.update(runtime.toAccessCtx(ctx, domain)))) notFound();

            await ctx.payload.restoreVersion({
                collection: manifest.collection as never,
                id: versionId,
                user: ctx.user as never,
                overrideAccess: false,
            });

            revalidateForManifest({ manifest, domain, doc: { id }, status: 'draft', revalidatePath });
        },
    };
};
