/**
 * Codegen for editor server-action wrappers.
 *
 * Reads `@nordcom/commerce-cms/editor/manifests` → emits one TypeScript file
 * per manifest into `apps/admin/src/lib/cms-actions/_generated/`.
 *
 * Each generated file re-exports the seven `EditorActions` methods as
 * top-level `'use server'` functions so Next.js can encode them as
 * transferable action IDs across the RSC boundary.
 *
 * Invoke via `pnpm cms:gen` (root) or `pnpm --filter @nordcom/commerce-cms cms:gen`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const OUTPUT_DIR = path.join(REPO_ROOT, 'apps/admin/src/lib/cms-actions/_generated');

const HEADER = `// AUTO-GENERATED by \`pnpm cms:gen\`. Do not edit by hand — changes will be
// overwritten the next time the generator runs. Edit the manifest that drives
// this file at packages/cms/src/editor/manifests/.
`;

const capitalize = (s: string): string => (s.length === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1));

const slugToCamel = (slug: string): string => slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

export const generateActionWrapper = (input: { slug: string; importName: string }): string => {
    const { slug, importName } = input;
    const camel = slugToCamel(slug);
    const fn = (method: string) => `${camel}${capitalize(method)}`;
    return `${HEADER}'use server';

import 'server-only';

import { createCollectionEditorActions } from '@nordcom/commerce-cms/editor';
import { ${importName} } from '@nordcom/commerce-cms/editor/manifests';

import { editorRuntime } from '@/lib/editor-runtime';

const a = createCollectionEditorActions(${importName}, editorRuntime);

export async function ${fn('saveDraft')}(domain: string | null, id: string, formData: FormData): Promise<void> {
    return a.saveDraft(domain, id, formData);
}
export async function ${fn('publish')}(domain: string | null, id: string, formData: FormData): Promise<void> {
    return a.publish(domain, id, formData);
}
export async function ${fn('create')}(domain: string | null, formData: FormData): Promise<{ id: string }> {
    return a.create(domain, formData);
}
export async function ${fn('delete')}(domain: string | null, id: string): Promise<void> {
    return a.delete(domain, id);
}
export async function ${fn('bulkDelete')}(domain: string | null, ids: string[]): Promise<void> {
    return a.bulkDelete(domain, ids);
}
export async function ${fn('bulkPublish')}(domain: string | null, ids: string[]): Promise<void> {
    return a.bulkPublish(domain, ids);
}
export async function ${fn('restoreVersion')}(domain: string | null, id: string, versionId: string): Promise<void> {
    return a.restoreVersion(domain, id, versionId);
}
`;
};

const slugToImportName = (slug: string): string => `${slugToCamel(slug)}Editor`;

const main = async (): Promise<void> => {
    const { allManifests } = await import('../src/editor/manifests/index.js');

    await mkdir(OUTPUT_DIR, { recursive: true });

    for (const manifest of allManifests) {
        const slug = String(manifest.collection);
        const importName = slugToImportName(slug);
        const output = generateActionWrapper({ slug, importName });
        const filePath = path.join(OUTPUT_DIR, `${slug}.ts`);
        await writeFile(filePath, output, 'utf-8');
        // biome-ignore lint/suspicious/noConsole: codegen script intentionally logs progress
        console.log(`[cms-gen] wrote ${path.relative(REPO_ROOT, filePath)}`);
    }
};

// Run when invoked directly: `tsx packages/cms/scripts/cms-gen.ts`
if (import.meta.url === `file://${process.argv[1]}`) {
    main().catch((err) => {
        // biome-ignore lint/suspicious/noConsole: codegen script reports failures to stderr
        console.error(err);
        process.exit(1);
    });
}
