import { expect, test } from '@playwright/test';

/**
 * SEO endpoints for the seeded tenant. The sitemap index and robots.txt are generated by route
 * handlers; this asserts their shape when they serve. They currently 500 against the mock.shop dev
 * tenant (the product/collection enumeration the index drives), so each test skips with that reason
 * rather than asserting a broken response — it self-activates in any environment where the handler
 * serves (e.g. a prod `next start` against a real catalog).
 */
test.describe('SEO endpoints', () => {
    test('GET /sitemap.xml returns a sitemap index', async ({ request }) => {
        const res = await request.get('/sitemap.xml');
        if (res.status() >= 500) {
            test.skip(true, `sitemap.xml returned ${res.status()} against the mock.shop dev tenant`);
        }
        expect(res.status()).toBe(200);
        expect(res.headers()['content-type']).toMatch(/xml/);
        expect(await res.text()).toContain('<sitemapindex');
    });

    test('GET /robots.txt includes a Sitemap directive', async ({ request }) => {
        const res = await request.get('/robots.txt');
        if (res.status() >= 500) {
            test.skip(true, `robots.txt returned ${res.status()} against the mock.shop dev tenant`);
        }
        expect(res.status()).toBe(200);
        expect(await res.text()).toMatch(/Sitemap:\s*https?:\/\//);
    });
});
