#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

reset=$(tput sgr0)
green='\033[1;32m'
red='\033[1;31m'

if hash bun 2>/dev/null; then
    echo -e "Running pre-commit hooks with ${green}bun${reset}"
    bunx concurrently "bun:lint" "bun:prettier" "bun:typecheck" "bun:test"
    bun run build
else
    echo -e "Runnin pre-commit hooks with ${red}npm${reset}"
    npx concurrently "npm:lint" "npm:prettier" "npm:typecheck" "npm:test"
    npm run build
fi
