// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticlePageDocumentDataSlicesSlice =
    | ColumnsSlice
    | ContentBlockSlice
    | BannerSlice
    | CollapsibleTextSlice
    | IconGridSlice
    | TextBlockSlice
    | ImageGridSlice
    | CollectionSlice
    | AlertSlice
    | VendorsSlice;

/**
 * Content for Article documents
 */
interface ArticlePageDocumentData {
    /**
     * Slice Zone field in *Article*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: article_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ArticlePageDocumentDataSlicesSlice> /**
     * Meta Image field in *Article*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: article_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Article*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: article_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    meta_description: prismic.RichTextField;

    /**
     * Keywords field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    keywords: prismic.KeyTextField;

    /**
     * noindex field in *Article*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: article_page.noindex
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    noindex: prismic.BooleanField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlePageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<ArticlePageDocumentData>,
    'article_page',
    Lang
>;

/**
 * Item in *Business Data → Social Profiles*
 */
export interface BusinessDataDocumentDataSocialProfilesItem {
    /**
     * href field in *Business Data → Social Profiles*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.social_profiles[].href
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    href: prismic.KeyTextField;
}

/**
 * Content for Business Data documents
 */
interface BusinessDataDocumentData {
    /**
     * Telephone field in *Business Data*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.telephone
     * - **Tab**: Basics
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    telephone: prismic.KeyTextField;

    /**
     * Email field in *Business Data*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.email
     * - **Tab**: Basics
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    email: prismic.KeyTextField /**
     * Social Profiles field in *Business Data*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.social_profiles[]
     * - **Tab**: Social
     * - **Documentation**: https://prismic.io/docs/field#group
     */;
    social_profiles: prismic.GroupField<Simplify<BusinessDataDocumentDataSocialProfilesItem>> /**
     * Legal Name field in *Business Data*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.legal_name
     * - **Tab**: Legal
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    legal_name: prismic.KeyTextField;

    /**
     * Tax Number field in *Business Data*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.tax_number
     * - **Tab**: Legal
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tax_number: prismic.KeyTextField;

    /**
     * VAT Number field in *Business Data*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: business_data.vat_number
     * - **Tab**: Legal
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    vat_number: prismic.KeyTextField;
}

/**
 * Business Data document from Prismic
 *
 * - **API ID**: `business_data`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BusinessDataDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<BusinessDataDocumentData>,
    'business_data',
    Lang
>;

type CartPageDocumentDataSlicesSlice =
    | IconGridSlice
    | VendorsSlice
    | ColumnsSlice
    | CollectionSlice
    | ImageGridSlice
    | TextBlockSlice
    | CollapsibleTextSlice
    | BannerSlice
    | ContentBlockSlice
    | AlertSlice;

type CartPageDocumentDataSidebarSlicesSlice =
    | IconGridSlice
    | ColumnsSlice
    | CollectionSlice
    | ImageGridSlice
    | VendorsSlice
    | TextBlockSlice
    | BannerSlice
    | CollapsibleTextSlice
    | ContentBlockSlice
    | AlertSlice;

type CartPageDocumentDataBottomSlicesSlice =
    | VendorsSlice
    | ColumnsSlice
    | CollectionSlice
    | ImageGridSlice
    | TextBlockSlice
    | IconGridSlice
    | CollapsibleTextSlice
    | BannerSlice
    | ContentBlockSlice
    | AlertSlice;

/**
 * Content for Cart documents
 */
interface CartPageDocumentData {
    /**
     * Slice Zone field in *Cart*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: cart_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CartPageDocumentDataSlicesSlice> /**
     * Meta Image field in *Cart*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cart_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Cart*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: cart_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Cart*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: cart_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    meta_description: prismic.RichTextField;

    /**
     * Keywords field in *Cart*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cart_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    keywords: prismic.KeyTextField;

    /**
     * noindex field in *Cart*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: cart_page.noindex
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    noindex: prismic.BooleanField /**
     * Slice Zone field in *Cart*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: cart_page.sidebar_slices[]
     * - **Tab**: Sidebar
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    sidebar_slices: prismic.SliceZone<CartPageDocumentDataSidebarSlicesSlice> /**
     * Slice Zone field in *Cart*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: cart_page.bottom_slices[]
     * - **Tab**: Bottom
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    bottom_slices: prismic.SliceZone<CartPageDocumentDataBottomSlicesSlice>;
}

/**
 * Cart document from Prismic
 *
 * - **API ID**: `cart_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CartPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CartPageDocumentData>,
    'cart_page',
    Lang
>;

type CollectionPageDocumentDataSlicesSlice =
    | OriginalContentSlice
    | CustomHtmlSlice
    | ContentBlockSlice
    | ColumnsSlice
    | AlertSlice
    | VendorsSlice
    | CollectionSlice
    | TextBlockSlice
    | BannerSlice
    | IconGridSlice
    | CollapsibleTextSlice
    | ImageGridSlice;

/**
 * Content for Collection documents
 */
interface CollectionPageDocumentData {
    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CollectionPageDocumentDataSlicesSlice> /**
     * Meta Image field in *Collection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: collection_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Collection*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: collection_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    meta_description: prismic.RichTextField;

    /**
     * Keywords field in *Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    keywords: prismic.KeyTextField;

    /**
     * noindex field in *Collection*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: collection_page.noindex
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    noindex: prismic.BooleanField;
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CollectionPageDocumentData>,
    'collection_page',
    Lang
>;

type ColumnDocumentDataSlicesSlice =
    | ColumnsSlice
    | CollectionSlice
    | VendorsSlice
    | TextBlockSlice
    | ImageGridSlice
    | IconGridSlice
    | CollapsibleTextSlice
    | BannerSlice
    | AlertSlice
    | ContentBlockSlice;

/**
 * Content for Column documents
 */
interface ColumnDocumentData {
    /**
     * Slice Zone field in *Column*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: column.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ColumnDocumentDataSlicesSlice>;
}

/**
 * Column document from Prismic
 *
 * - **API ID**: `column`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColumnDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<ColumnDocumentData>,
    'column',
    Lang
>;

type CustomPageDocumentDataSlicesSlice =
    | CustomHtmlSlice
    | ColumnsSlice
    | ContentBlockSlice
    | CollectionSlice
    | ImageGridSlice
    | TextBlockSlice
    | CollapsibleTextSlice
    | VendorsSlice
    | IconGridSlice
    | AlertSlice
    | BannerSlice;

/**
 * Content for Page documents
 */
interface CustomPageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CustomPageDocumentDataSlicesSlice> /**
     * Meta Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: custom_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: custom_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    meta_description: prismic.RichTextField;

    /**
     * Keywords field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    keywords: prismic.KeyTextField;

    /**
     * noindex field in *Page*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: custom_page.noindex
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    noindex: prismic.BooleanField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `custom_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CustomPageDocumentData>,
    'custom_page',
    Lang
>;

/**
 * Item in *Footer → Policy Links*
 */
export interface FooterDocumentDataPolicyLinksItem {
    /**
     * Title field in *Footer → Policy Links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.policy_links[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * href field in *Footer → Policy Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.policy_links[].href
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    href: prismic.LinkField;
}

/**
 * Primary content in *Footer → Slice Zone → Block → Primary*
 */
export interface FooterDocumentDataBodyBlockSlicePrimary {
    /**
     * Title field in *Footer → Slice Zone → Block → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Item content in *Footer → Slice Zone → Block → Items*
 */
export interface FooterDocumentDataBodyBlockSliceItem {
    /**
     * Title field in *Footer → Slice Zone → Block → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.items.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Handle field in *Footer → Slice Zone → Block → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.items.handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;
}

/**
 * Slice for *Footer → Slice Zone*
 */
export type FooterDocumentDataBodyBlockSlice = prismic.Slice<
    'block',
    Simplify<FooterDocumentDataBodyBlockSlicePrimary>,
    Simplify<FooterDocumentDataBodyBlockSliceItem>
>;

type FooterDocumentDataBodySlice = FooterDocumentDataBodyBlockSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
    /**
     * Address field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    address: prismic.RichTextField;

    /**
     * Copyrights field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: © 2023-2024 Nordcom AB
     * - **API ID Path**: footer.copyrights
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    copyrights: prismic.RichTextField;

    /**
     * Policy Links field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.policy_links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    policy_links: prismic.GroupField<Simplify<FooterDocumentDataPolicyLinksItem>>;

    /**
     * Custom HTML field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: <div>hello world!</div>
     * - **API ID Path**: footer.custom_html
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    custom_html: prismic.KeyTextField;

    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    body: prismic.SliceZone<FooterDocumentDataBodySlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    'footer',
    Lang
>;

type HeaderDocumentDataSlicesSlice = CustomHtmlSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
    /**
     * Slice Zone field in *Header*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: header.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    'header',
    Lang
>;

type MenuDocumentDataSlicesSlice = DropdownSlice | LinkSlice;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
    /**
     * Support Phone Number field in *Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: +46 70-241 29 07
     * - **API ID Path**: menu.phone
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    phone: prismic.KeyTextField;

    /**
     * Support Email field in *Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: hi@nordcom.io
     * - **API ID Path**: menu.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    email: prismic.KeyTextField;

    /**
     * Show Info Bar field in *Menu*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: menu.show_info_bar
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    show_info_bar: prismic.BooleanField;

    /**
     * Slice Zone field in *Menu*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<MenuDocumentDataSlicesSlice>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<MenuDocumentData>,
    'menu',
    Lang
>;

type MenuItemDocumentDataSlicesSlice = never;

/**
 * Content for Menu Item documents
 */
interface MenuItemDocumentData {
    /**
     * Title field in *Menu Item*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The name/title of the menu
     * - **API ID Path**: menu_item.title
     * - **Tab**: MenuItem
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Slice Zone field in *Menu Item*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu_item.slices[]
     * - **Tab**: MenuItem
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<MenuItemDocumentDataSlicesSlice>;
}

/**
 * Menu Item document from Prismic
 *
 * - **API ID**: `menu_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuItemDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<MenuItemDocumentData>,
    'menu_item',
    Lang
>;

type ProductPageDocumentDataSlicesSlice =
    | ContentBlockSlice
    | ColumnsSlice
    | TextBlockSlice
    | VendorsSlice
    | ImageGridSlice
    | CollectionSlice
    | AlertSlice
    | IconGridSlice
    | CollapsibleTextSlice
    | BannerSlice;

type ProductPageDocumentDataSlices2Slice =
    | ContentBlockSlice
    | ColumnsSlice
    | BannerSlice
    | AlertSlice
    | CollectionSlice
    | TextBlockSlice
    | ImageGridSlice
    | IconGridSlice
    | VendorsSlice
    | CollapsibleTextSlice;

/**
 * Content for Product documents
 */
interface ProductPageDocumentData {
    /**
     * Slice Zone field in *Product*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProductPageDocumentDataSlicesSlice> /**
     * Meta Image field in *Product*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Product*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: product_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Product*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: product_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    meta_description: prismic.RichTextField;

    /**
     * Keywords field in *Product*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    keywords: prismic.KeyTextField;

    /**
     * noindex field in *Product*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: product_page.noindex
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    noindex: prismic.BooleanField /**
     * Slice Zone field in *Product*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.slices2[]
     * - **Tab**: Secondary
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices2: prismic.SliceZone<ProductPageDocumentDataSlices2Slice>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<ProductPageDocumentData>,
    'product_page',
    Lang
>;

/**
 * Item in *Store → DEPRECATED - Currencies*
 */
export interface StoreDocumentDataCurrenciesItem {
    /**
     * DEPRECATED - currency field in *Store → DEPRECATED - Currencies*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.currencies[].currency
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    currency: prismic.KeyTextField;
}

/**
 * Content for Store documents
 */
interface StoreDocumentData {
    /**
     * Store name field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Sweet Side of Sweden
     * - **API ID Path**: store.store_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    store_name: prismic.KeyTextField;

    /**
     * Description field in *Store*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Description of the store
     * - **API ID Path**: store.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;

    /**
     * DEPRECATED - Logo field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    logo: prismic.KeyTextField;

    /**
     * DEPRECATED - Favicon field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.favicon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    favicon: prismic.KeyTextField;

    /**
     * DEPRECATED - Currencies field in *Store*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: store.currencies[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    currencies: prismic.GroupField<Simplify<StoreDocumentDataCurrenciesItem>> /**
     * Primary Logo field in *Store*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logos_primary
     * - **Tab**: Logos
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    logos_primary: prismic.ImageField<never>;

    /**
     * Alternative Logo field in *Store*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logos_alternative
     * - **Tab**: Logos
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logos_alternative: prismic.ImageField<never>;

    /**
     * Favicon field in *Store*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logos_favicon
     * - **Tab**: Logos
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logos_favicon: prismic.ImageField<never> /**
     * Primary field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: #cce2cb
     * - **API ID Path**: store.colors_primary
     * - **Tab**: Colors
     * - **Documentation**: https://prismic.io/docs/field#color
     */;
    colors_primary: prismic.ColorField;

    /**
     * Secondary field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: store.colors_secondary
     * - **Tab**: Colors
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    colors_secondary: prismic.ColorField;
}

/**
 * Store document from Prismic
 *
 * - **API ID**: `store`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoreDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<StoreDocumentData>,
    'store',
    Lang
>;

export type AllDocumentTypes =
    | ArticlePageDocument
    | BusinessDataDocument
    | CartPageDocument
    | CollectionPageDocument
    | ColumnDocument
    | CustomPageDocument
    | FooterDocument
    | HeaderDocument
    | MenuDocument
    | MenuItemDocument
    | ProductPageDocument
    | StoreDocument;

/**
 * Primary content in *Alert → Default → Primary*
 */
export interface AlertSliceDefaultPrimary {
    /**
     * Severity field in *Alert → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: info
     * - **API ID Path**: alert.default.primary.severity
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    severity: prismic.SelectField<'info' | 'success' | 'warning' | 'error' | 'callout', 'filled'>;

    /**
     * Content field in *Alert → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: alert.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;

    /**
     * Icon field in *Alert → Default → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: alert.default.primary.show_icon
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    show_icon: prismic.BooleanField;
}

/**
 * Default variation for Alert Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlertSliceDefault = prismic.SharedSliceVariation<'default', Simplify<AlertSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Alert*
 */
type AlertSliceVariation = AlertSliceDefault;

/**
 * Alert Shared Slice
 *
 * - **API ID**: `alert`
 * - **Description**: Alert
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlertSlice = prismic.SharedSlice<'alert', AlertSliceVariation>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
    /**
     * Primary content field in *Banner → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceDefaultItem {
    /**
     * Title field in *Banner → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Target field in *Banner → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].target
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    target: prismic.LinkField;

    /**
     * Button field in *Banner → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: banner.items[].type
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    type: prismic.BooleanField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<BannerSliceDefaultPrimary>,
    Simplify<BannerSliceDefaultItem>
>;

/**
 * Primary content in *Banner → Aside → Primary*
 */
export interface BannerSliceAsidePrimary {
    /**
     * Primary content field in *Banner → Aside → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.aside.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;

    /**
     * Background field in *Banner → Aside → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.aside.primary.background
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    background: prismic.ImageField<never>;

    /**
     * Image field in *Banner → Aside → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.aside.primary.image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Text color field in *Banner → Aside → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.aside.primary.text_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    text_color: prismic.ColorField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceAsideItem {
    /**
     * Title field in *Banner → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Target field in *Banner → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].target
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    target: prismic.LinkField;

    /**
     * Button field in *Banner → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: banner.items[].type
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    type: prismic.BooleanField;
}

/**
 * Aside variation for Banner Slice
 *
 * - **API ID**: `aside`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceAside = prismic.SharedSliceVariation<
    'aside',
    Simplify<BannerSliceAsidePrimary>,
    Simplify<BannerSliceAsideItem>
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceAside;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<'banner', BannerSliceVariation>;

/**
 * Primary content in *CollapsibleText → Default → Primary*
 */
export interface CollapsibleTextSliceDefaultPrimary {
    /**
     * Title field in *CollapsibleText → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Text field in *CollapsibleText → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.default.primary.text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField;
}

/**
 * Default variation for CollapsibleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapsibleTextSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CollapsibleTextSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *CollapsibleText*
 */
type CollapsibleTextSliceVariation = CollapsibleTextSliceDefault;

/**
 * CollapsibleText Shared Slice
 *
 * - **API ID**: `collapsible_text`
 * - **Description**: CollapsibleText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapsibleTextSlice = prismic.SharedSlice<'collapsible_text', CollapsibleTextSliceVariation>;

/**
 * Primary content in *Collection → Default → Primary*
 */
export interface CollectionSliceDefaultPrimary {
    /**
     * Handle field in *Collection → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.default.primary.handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;

    /**
     * Title field in *Collection → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Body field in *Collection → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.default.primary.body
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    body: prismic.RichTextField;

    /**
     * Alignment field in *Collection → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: left
     * - **API ID Path**: collection.default.primary.alignment
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    alignment: prismic.SelectField<'left' | 'center' | 'right', 'filled'>;

    /**
     * Item Limit field in *Collection → Default → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 16
     * - **API ID Path**: collection.default.primary.limit
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    limit: prismic.NumberField;

    /**
     * Direction field in *Collection → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: horizontal
     * - **API ID Path**: collection.default.primary.direction
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    direction: prismic.SelectField<'horizontal' | 'grid', 'filled'>;

    /**
     * View All Card field in *Collection → Default → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: collection.default.primary.show_view_all_card
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    show_view_all_card: prismic.BooleanField;

    /**
     * Display field in *Collection → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: in-container
     * - **API ID Path**: collection.default.primary.display
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    display: prismic.SelectField<'in-container' | 'full-width', 'filled'>;
}

/**
 * Default variation for Collection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CollectionSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Collection*
 */
type CollectionSliceVariation = CollectionSliceDefault;

/**
 * Collection Shared Slice
 *
 * - **API ID**: `collection`
 * - **Description**: Collection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionSlice = prismic.SharedSlice<'collection', CollectionSliceVariation>;

/**
 * Item in *Columns → Default → Primary → Items*
 */
export interface ColumnsSliceDefaultPrimaryChildrenItem {
    /**
     * Column field in *Columns → Default → Primary → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: columns.default.primary.children[].column
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    column: prismic.ContentRelationshipField<'column'>;
}

/**
 * Primary content in *Columns → Default → Primary*
 */
export interface ColumnsSliceDefaultPrimary {
    /**
     * Items field in *Columns → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: columns.default.primary.children[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    children: prismic.GroupField<Simplify<ColumnsSliceDefaultPrimaryChildrenItem>>;
}

/**
 * Default variation for Columns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColumnsSliceDefault = prismic.SharedSliceVariation<'default', Simplify<ColumnsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Columns*
 */
type ColumnsSliceVariation = ColumnsSliceDefault;

/**
 * Columns Shared Slice
 *
 * - **API ID**: `columns`
 * - **Description**: Columns
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColumnsSlice = prismic.SharedSlice<'columns', ColumnsSliceVariation>;

/**
 * Primary content in *ContentBlock → Default → Primary*
 */
export interface ContentBlockSliceDefaultPrimary {
    /**
     * Text field in *ContentBlock → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_block.default.primary.text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField;

    /**
     * Width field in *ContentBlock → Default → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: content_block.default.primary.width
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    width: prismic.BooleanField;
}

/**
 * Default variation for ContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ContentBlockSliceDefaultPrimary>,
    never
>;

/**
 * Primary content in *ContentBlock → Card → Primary*
 */
export interface ContentBlockSliceCardPrimary {
    /**
     * Text field in *ContentBlock → Card → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_block.card.primary.text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField;

    /**
     * Border field in *ContentBlock → Card → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: content_block.card.primary.border
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    border: prismic.BooleanField;

    /**
     * Width field in *ContentBlock → Card → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: content_block.card.primary.width
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    width: prismic.BooleanField;
}

/**
 * Card variation for ContentBlock Slice
 *
 * - **API ID**: `card`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceCard = prismic.SharedSliceVariation<'card', Simplify<ContentBlockSliceCardPrimary>, never>;

/**
 * Slice variation for *ContentBlock*
 */
type ContentBlockSliceVariation = ContentBlockSliceDefault | ContentBlockSliceCard;

/**
 * ContentBlock Shared Slice
 *
 * - **API ID**: `content_block`
 * - **Description**: ContentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSlice = prismic.SharedSlice<'content_block', ContentBlockSliceVariation>;

/**
 * Primary content in *CustomHTML → Default → Primary*
 */
export interface CustomHtmlSliceDefaultPrimary {
    /**
     * HTML field in *CustomHTML → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_html.default.primary.html
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    html: prismic.KeyTextField;
}

/**
 * Default variation for CustomHTML Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomHtmlSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CustomHtmlSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *CustomHTML*
 */
type CustomHtmlSliceVariation = CustomHtmlSliceDefault;

/**
 * CustomHTML Shared Slice
 *
 * - **API ID**: `custom_html`
 * - **Description**: CustomHTML
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomHtmlSlice = prismic.SharedSlice<'custom_html', CustomHtmlSliceVariation>;

/**
 * Primary content in *IconGrid → Default → Primary*
 */
export interface IconGridSliceDefaultPrimary {
    /**
     * Background Color field in *IconGrid → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: primary
     * - **API ID Path**: icon_grid.default.primary.background
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    background: prismic.SelectField<'primary' | 'secondary', 'filled'>;
}

/**
 * Primary content in *IconGrid → Items*
 */
export interface IconGridSliceDefaultItem {
    /**
     * Icon field in *IconGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_grid.items[].icon
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    icon: prismic.ImageField<never>;

    /**
     * Title field in *IconGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Default variation for IconGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<IconGridSliceDefaultPrimary>,
    Simplify<IconGridSliceDefaultItem>
>;

/**
 * Slice variation for *IconGrid*
 */
type IconGridSliceVariation = IconGridSliceDefault;

/**
 * IconGrid Shared Slice
 *
 * - **API ID**: `icon_grid`
 * - **Description**: IconGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconGridSlice = prismic.SharedSlice<'icon_grid', IconGridSliceVariation>;

/**
 * Primary content in *ImageGrid → Items*
 */
export interface ImageGridSliceDefaultItem {
    /**
     * Image field in *ImageGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * href field in *ImageGrid → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].href
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    href: prismic.LinkField;

    /**
     * Title field in *ImageGrid → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Description field in *ImageGrid → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ImageGridSliceDefaultItem>
>;

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridSliceVariation = ImageGridSliceDefault;

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: ImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSlice = prismic.SharedSlice<'image_grid', ImageGridSliceVariation>;

/**
 * Default variation for OriginalContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OriginalContentSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *OriginalContent*
 */
type OriginalContentSliceVariation = OriginalContentSliceDefault;

/**
 * OriginalContent Shared Slice
 *
 * - **API ID**: `original_content`
 * - **Description**: OriginalContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OriginalContentSlice = prismic.SharedSlice<'original_content', OriginalContentSliceVariation>;

/**
 * Primary content in *Overview → Items*
 */
export interface TextBlockSliceDefaultItem {
    /**
     * Layout field in *Overview → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Image on the left or the right?
     * - **Default Value**: left
     * - **API ID Path**: text_block.items[].layout
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    layout: prismic.SelectField<'left' | 'right' | 'center', 'filled'>;

    /**
     * Accent field in *Overview → Items*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.items[].accent
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    accent: prismic.ColorField;

    /**
     * Image field in *Overview → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Image Style field in *Overview → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: normal
     * - **API ID Path**: text_block.items[].image_style
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    image_style: prismic.SelectField<'normal' | 'cover', 'filled'>;

    /**
     * Text field in *Overview → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Content
     * - **API ID Path**: text_block.items[].text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField;
}

/**
 * Default variation for Overview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image on the left side
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<TextBlockSliceDefaultItem>
>;

/**
 * Slice variation for *Overview*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * Overview Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: An image with a textblock to the side of it
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<'text_block', TextBlockSliceVariation>;

/**
 * Default variation for Vendors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VendorsSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *Vendors*
 */
type VendorsSliceVariation = VendorsSliceDefault;

/**
 * Vendors Shared Slice
 *
 * - **API ID**: `vendors`
 * - **Description**: Vendors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VendorsSlice = prismic.SharedSlice<'vendors', VendorsSliceVariation>;

/**
 * Item in *Dropdown → Default → Primary → Links*
 */
export interface DropdownSliceDefaultPrimaryLinksItem {
    /**
     * Title field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.links[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * href field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.links[].href
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    href: prismic.LinkField;

    /**
     * Image (optional) field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.links[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<'desktop' | 'large desktop'>;

    /**
     * Background Color (optional) field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.links[].background_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_color: prismic.ColorField;

    /**
     * Image Position (optional) field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: center
     * - **API ID Path**: dropdown.default.primary.links[].image_position
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    image_position: prismic.SelectField<'center' | 'right' | 'left' | 'top' | 'bottom', 'filled'>;

    /**
     * Description (optional) field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.links[].description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;

    /**
     * Shadow field in *Dropdown → Default → Primary → Links*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: dropdown.default.primary.links[].shadow
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    shadow: prismic.BooleanField;
}

/**
 * Primary content in *Dropdown → Default → Primary*
 */
export interface DropdownSliceDefaultPrimary {
    /**
     * Title field in *Dropdown → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Links field in *Dropdown → Default → Primary*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: dropdown.default.primary.links[]
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    links: prismic.GroupField<Simplify<DropdownSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Dropdown Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DropdownSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<DropdownSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Dropdown*
 */
type DropdownSliceVariation = DropdownSliceDefault;

/**
 * Dropdown Shared Slice
 *
 * - **API ID**: `dropdown`
 * - **Description**: Dropdown
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DropdownSlice = prismic.SharedSlice<'dropdown', DropdownSliceVariation>;

/**
 * Primary content in *Link → Default → Primary*
 */
export interface LinkSliceDefaultPrimary {
    /**
     * Title field in *Link → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: link.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * href field in *Link → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: link.default.primary.href
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    href: prismic.LinkField;
}

/**
 * Default variation for Link Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceDefault = prismic.SharedSliceVariation<'default', Simplify<LinkSliceDefaultPrimary>, never>;

/**
 * Primary content in *Link → Highlighted → Primary*
 */
export interface LinkSliceHighlightedPrimary {
    /**
     * Title field in *Link → Highlighted → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: link.highlighted.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * href field in *Link → Highlighted → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: link.highlighted.primary.href
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    href: prismic.LinkField;
}

/**
 * Highlighted variation for Link Slice
 *
 * - **API ID**: `highlighted`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceHighlighted = prismic.SharedSliceVariation<
    'highlighted',
    Simplify<LinkSliceHighlightedPrimary>,
    never
>;

/**
 * Slice variation for *Link*
 */
type LinkSliceVariation = LinkSliceDefault | LinkSliceHighlighted;

/**
 * Link Shared Slice
 *
 * - **API ID**: `link`
 * - **Description**: Link
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSlice = prismic.SharedSlice<'link', LinkSliceVariation>;

declare module '@prismicio/client' {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            ArticlePageDocument,
            ArticlePageDocumentData,
            ArticlePageDocumentDataSlicesSlice,
            BusinessDataDocument,
            BusinessDataDocumentData,
            BusinessDataDocumentDataSocialProfilesItem,
            CartPageDocument,
            CartPageDocumentData,
            CartPageDocumentDataSlicesSlice,
            CartPageDocumentDataSidebarSlicesSlice,
            CartPageDocumentDataBottomSlicesSlice,
            CollectionPageDocument,
            CollectionPageDocumentData,
            CollectionPageDocumentDataSlicesSlice,
            ColumnDocument,
            ColumnDocumentData,
            ColumnDocumentDataSlicesSlice,
            CustomPageDocument,
            CustomPageDocumentData,
            CustomPageDocumentDataSlicesSlice,
            FooterDocument,
            FooterDocumentData,
            FooterDocumentDataPolicyLinksItem,
            FooterDocumentDataBodyBlockSlicePrimary,
            FooterDocumentDataBodyBlockSliceItem,
            FooterDocumentDataBodySlice,
            HeaderDocument,
            HeaderDocumentData,
            HeaderDocumentDataSlicesSlice,
            MenuDocument,
            MenuDocumentData,
            MenuDocumentDataSlicesSlice,
            MenuItemDocument,
            MenuItemDocumentData,
            MenuItemDocumentDataSlicesSlice,
            ProductPageDocument,
            ProductPageDocumentData,
            ProductPageDocumentDataSlicesSlice,
            ProductPageDocumentDataSlices2Slice,
            StoreDocument,
            StoreDocumentData,
            StoreDocumentDataCurrenciesItem,
            AllDocumentTypes,
            AlertSlice,
            AlertSliceDefaultPrimary,
            AlertSliceVariation,
            AlertSliceDefault,
            BannerSlice,
            BannerSliceDefaultPrimary,
            BannerSliceDefaultItem,
            BannerSliceAsidePrimary,
            BannerSliceAsideItem,
            BannerSliceVariation,
            BannerSliceDefault,
            BannerSliceAside,
            CollapsibleTextSlice,
            CollapsibleTextSliceDefaultPrimary,
            CollapsibleTextSliceVariation,
            CollapsibleTextSliceDefault,
            CollectionSlice,
            CollectionSliceDefaultPrimary,
            CollectionSliceVariation,
            CollectionSliceDefault,
            ColumnsSlice,
            ColumnsSliceDefaultPrimaryChildrenItem,
            ColumnsSliceDefaultPrimary,
            ColumnsSliceVariation,
            ColumnsSliceDefault,
            ContentBlockSlice,
            ContentBlockSliceDefaultPrimary,
            ContentBlockSliceCardPrimary,
            ContentBlockSliceVariation,
            ContentBlockSliceDefault,
            ContentBlockSliceCard,
            CustomHtmlSlice,
            CustomHtmlSliceDefaultPrimary,
            CustomHtmlSliceVariation,
            CustomHtmlSliceDefault,
            IconGridSlice,
            IconGridSliceDefaultPrimary,
            IconGridSliceDefaultItem,
            IconGridSliceVariation,
            IconGridSliceDefault,
            ImageGridSlice,
            ImageGridSliceDefaultItem,
            ImageGridSliceVariation,
            ImageGridSliceDefault,
            OriginalContentSlice,
            OriginalContentSliceVariation,
            OriginalContentSliceDefault,
            TextBlockSlice,
            TextBlockSliceDefaultItem,
            TextBlockSliceVariation,
            TextBlockSliceDefault,
            VendorsSlice,
            VendorsSliceVariation,
            VendorsSliceDefault,
            DropdownSlice,
            DropdownSliceDefaultPrimaryLinksItem,
            DropdownSliceDefaultPrimary,
            DropdownSliceVariation,
            DropdownSliceDefault,
            LinkSlice,
            LinkSliceDefaultPrimary,
            LinkSliceHighlightedPrimary,
            LinkSliceVariation,
            LinkSliceDefault,
            LinkSliceHighlighted
        };
    }
}
