// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticlePageDocumentDataSlicesSlice = AlertSlice | VendorsSlice;

/**
 * Content for Article documents
 */
interface ArticlePageDocumentData {
    /**
     * Slice Zone field in *Article*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: article_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ArticlePageDocumentDataSlicesSlice> /**
     * Meta Description field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: article_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Article*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: article_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlePageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<ArticlePageDocumentData>,
    'article_page',
    Lang
>;

type CollectionPageDocumentDataSlicesSlice =
    | TitleSlice
    | AlertSlice
    | VendorsSlice
    | CollectionSlice
    | TextBlockSlice
    | BannerSlice
    | IconGridSlice
    | CollapsibleTextSlice
    | ImageGridSlice
    | CarouselSlice
    | SpacingSlice;

/**
 * Content for Collection documents
 */
interface CollectionPageDocumentData {
    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CollectionPageDocumentDataSlicesSlice> /**
     * Meta Title field in *Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: collection_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Collection*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: collection_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    meta_description: prismic.RichTextField;

    /**
     * Meta Image field in *Collection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CollectionPageDocumentData>,
    'collection_page',
    Lang
>;

type CustomPageDocumentDataSlicesSlice =
    | CarouselSlice
    | CollectionSlice
    | ImageGridSlice
    | TextBlockSlice
    | CollapsibleTextSlice
    | VendorsSlice
    | IconGridSlice
    | AlertSlice
    | BannerSlice
    | SpacingSlice
    | TitleSlice;

/**
 * Content for Page documents
 */
interface CustomPageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Show built-in header field in *Page*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: custom_page.enable_header
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    enable_header: prismic.BooleanField;

    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CustomPageDocumentDataSlicesSlice> /**
     * Meta Description field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: custom_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */;
    meta_description: prismic.RichTextField;

    /**
     * Meta Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: custom_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;

    /**
     * Keywords field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: custom_page.keywords
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    keywords: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `custom_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CustomPageDocumentData>,
    'custom_page',
    Lang
>;

/**
 * Primary content in *Footer → Slice Zone → Block → Primary*
 */
export interface FooterDocumentDataBodyBlockSlicePrimary {
    /**
     * Title field in *Footer → Slice Zone → Block → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Item content in *Footer → Slice Zone → Block → Items*
 */
export interface FooterDocumentDataBodyBlockSliceItem {
    /**
     * Title field in *Footer → Slice Zone → Block → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.items.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Handle field in *Footer → Slice Zone → Block → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[].block.items.handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;
}

/**
 * Slice for *Footer → Slice Zone*
 */
export type FooterDocumentDataBodyBlockSlice = prismic.Slice<
    'block',
    Simplify<FooterDocumentDataBodyBlockSlicePrimary>,
    Simplify<FooterDocumentDataBodyBlockSliceItem>
>;

type FooterDocumentDataBodySlice = FooterDocumentDataBodyBlockSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
    /**
     * Address field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    address: prismic.RichTextField;

    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    body: prismic.SliceZone<FooterDocumentDataBodySlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    'footer',
    Lang
>;

/**
 * Item in *Header → Announcements*
 */
export interface HeadDocumentDataAnnouncementsItem {
    /**
     * Location field in *Header → Announcements*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: above
     * - **API ID Path**: head.announcements[].location
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    location: prismic.SelectField<'above' | 'bellow', 'filled'>;

    /**
     * Background Color field in *Header → Announcements*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: secondary
     * - **API ID Path**: head.announcements[].background_color
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    background_color: prismic.SelectField<'secondary' | 'primary', 'filled'>;

    /**
     * Content field in *Header → Announcements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Free shipping on orders above $75
     * - **API ID Path**: head.announcements[].content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;
}

/**
 * Item in *Header → Navigation*
 */
export interface HeadDocumentDataNavigationItem {
    /**
     * Menu field in *Header → Navigation*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: head.navigation[].menu
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    menu: prismic.ContentRelationshipField<'menu_item'>;
}

/**
 * Content for Header documents
 */
interface HeadDocumentData {
    /**
     * Announcements field in *Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: head.announcements[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    announcements: prismic.GroupField<Simplify<HeadDocumentDataAnnouncementsItem>>;

    /**
     * Navigation field in *Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: head.navigation[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    navigation: prismic.GroupField<Simplify<HeadDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `head`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeadDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<HeadDocumentData>,
    'head',
    Lang
>;

type MenuItemDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for MenuItem documents
 */
interface MenuItemDocumentData {
    /**
     * Title field in *MenuItem*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The name/title of the menu
     * - **API ID Path**: menu_item.title
     * - **Tab**: MenuItem
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Slice Zone field in *MenuItem*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu_item.slices[]
     * - **Tab**: MenuItem
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<MenuItemDocumentDataSlicesSlice>;
}

/**
 * MenuItem document from Prismic
 *
 * - **API ID**: `menu_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuItemDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<MenuItemDocumentData>,
    'menu_item',
    Lang
>;

/**
 * Primary content in *Navigation → Slice Zone → Link → Primary*
 */
export interface NavigationDocumentDataBodyLinkSlicePrimary {
    /**
     * Title field in *Navigation → Slice Zone → Link → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Handle field in *Navigation → Slice Zone → Link → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.primary.handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;
}

/**
 * Item content in *Navigation → Slice Zone → Link → Items*
 */
export interface NavigationDocumentDataBodyLinkSliceItem {
    /**
     * Title field in *Navigation → Slice Zone → Link → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.items.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Description field in *Navigation → Slice Zone → Link → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.items.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Handle field in *Navigation → Slice Zone → Link → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[].link.items.handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;
}

/**
 * Slice for *Navigation → Slice Zone*
 */
export type NavigationDocumentDataBodyLinkSlice = prismic.Slice<
    'link',
    Simplify<NavigationDocumentDataBodyLinkSlicePrimary>,
    Simplify<NavigationDocumentDataBodyLinkSliceItem>
>;

type NavigationDocumentDataBodySlice = NavigationDocumentDataBodyLinkSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    body: prismic.SliceZone<NavigationDocumentDataBodySlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
>;

type ProductPageDocumentDataSlicesSlice = ProductDescriptionSlice;

type ProductPageDocumentDataSlices2Slice =
    | CollectionSlice
    | CarouselSlice
    | TextBlockSlice
    | ImageGridSlice
    | IconGridSlice
    | VendorsSlice
    | CollapsibleTextSlice;

/**
 * Content for Product documents
 */
interface ProductPageDocumentData {
    /**
     * Slice Zone field in *Product*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProductPageDocumentDataSlicesSlice> /**
     * Meta Description field in *Product*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: product_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */;
    meta_description: prismic.RichTextField;

    /**
     * Meta Image field in *Product*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Product*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: product_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField /**
     * Slice Zone field in *Product*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: product_page.slices2[]
     * - **Tab**: Secondary
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices2: prismic.SliceZone<ProductPageDocumentDataSlices2Slice>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<ProductPageDocumentData>,
    'product_page',
    Lang
>;

/**
 * Item in *Store → DEPRECATED - Currencies*
 */
export interface StoreDocumentDataCurrenciesItem {
    /**
     * DEPRECATED - currency field in *Store → DEPRECATED - Currencies*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.currencies[].currency
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    currency: prismic.KeyTextField;
}

/**
 * Content for Store documents
 */
interface StoreDocumentData {
    /**
     * Store name field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Sweet Side of Sweden
     * - **API ID Path**: store.store_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    store_name: prismic.KeyTextField;

    /**
     * Description field in *Store*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Description of the store
     * - **API ID Path**: store.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;

    /**
     * DEPRECATED - Logo field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    logo: prismic.KeyTextField;

    /**
     * DEPRECATED - Favicon field in *Store*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: store.favicon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    favicon: prismic.KeyTextField;

    /**
     * DEPRECATED - Currencies field in *Store*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: store.currencies[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    currencies: prismic.GroupField<Simplify<StoreDocumentDataCurrenciesItem>> /**
     * Primary Logo field in *Store*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logos_primary
     * - **Tab**: Logos
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    logos_primary: prismic.ImageField<never>;

    /**
     * Alternative Logo field in *Store*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logos_alternative
     * - **Tab**: Logos
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logos_alternative: prismic.ImageField<never>;

    /**
     * Favicon field in *Store*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: store.logos_favicon
     * - **Tab**: Logos
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logos_favicon: prismic.ImageField<never> /**
     * Primary field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: #cce2cb
     * - **API ID Path**: store.colors_primary
     * - **Tab**: Colors
     * - **Documentation**: https://prismic.io/docs/field#color
     */;
    colors_primary: prismic.ColorField;

    /**
     * Secondary field in *Store*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: store.colors_secondary
     * - **Tab**: Colors
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    colors_secondary: prismic.ColorField;
}

/**
 * Store document from Prismic
 *
 * - **API ID**: `store`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoreDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<StoreDocumentData>,
    'store',
    Lang
>;

export type AllDocumentTypes =
    | ArticlePageDocument
    | CollectionPageDocument
    | CustomPageDocument
    | FooterDocument
    | HeadDocument
    | MenuItemDocument
    | NavigationDocument
    | ProductPageDocument
    | StoreDocument;

/**
 * Primary content in *Alert → Default → Primary*
 */
export interface AlertSliceDefaultPrimary {
    /**
     * Severity field in *Alert → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: info
     * - **API ID Path**: alert.default.primary.severity
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    severity: prismic.SelectField<'info' | 'success' | 'warning' | 'error', 'filled'>;

    /**
     * Content field in *Alert → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: alert.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;
}

/**
 * Default variation for Alert Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlertSliceDefault = prismic.SharedSliceVariation<'default', Simplify<AlertSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Alert*
 */
type AlertSliceVariation = AlertSliceDefault;

/**
 * Alert Shared Slice
 *
 * - **API ID**: `alert`
 * - **Description**: Alert
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlertSlice = prismic.SharedSlice<'alert', AlertSliceVariation>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
    /**
     * Primary content field in *Banner → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;

    /**
     * Background field in *Banner → Default → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: #cce2cb
     * - **API ID Path**: banner.default.primary.background
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background: prismic.ColorField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceDefaultItem {
    /**
     * Title field in *Banner → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Target field in *Banner → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].target
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    target: prismic.LinkField;

    /**
     * Button field in *Banner → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: banner.items[].type
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    type: prismic.BooleanField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<BannerSliceDefaultPrimary>,
    Simplify<BannerSliceDefaultItem>
>;

/**
 * Primary content in *Banner → Simple - Slim → Primary*
 */
export interface BannerSliceSimpleSlimPrimary {
    /**
     * Primary content field in *Banner → Simple - Slim → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.simpleSlim.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;

    /**
     * Background field in *Banner → Simple - Slim → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: #cce2cb
     * - **API ID Path**: banner.simpleSlim.primary.background
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background: prismic.ColorField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceSimpleSlimItem {
    /**
     * Title field in *Banner → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Target field in *Banner → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].target
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    target: prismic.LinkField;

    /**
     * Button field in *Banner → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: banner.items[].type
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    type: prismic.BooleanField;
}

/**
 * Simple - Slim variation for Banner Slice
 *
 * - **API ID**: `simpleSlim`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceSimpleSlim = prismic.SharedSliceVariation<
    'simpleSlim',
    Simplify<BannerSliceSimpleSlimPrimary>,
    Simplify<BannerSliceSimpleSlimItem>
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceSimpleSlim;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<'banner', BannerSliceVariation>;

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
    /**
     * Delay field in *Carousel → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: 3000
     * - **API ID Path**: carousel.default.primary.delay
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    delay: prismic.KeyTextField;
}

/**
 * Primary content in *Carousel → Items*
 */
export interface CarouselSliceDefaultItem {
    /**
     * Image field in *Carousel → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Carousel → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * href field in *Carousel → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel.items[].href
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    href: prismic.KeyTextField;

    /**
     * Defer field in *Carousel → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: carousel.items[].defer
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    defer: prismic.BooleanField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CarouselSliceDefaultPrimary>,
    Simplify<CarouselSliceDefaultItem>
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<'carousel', CarouselSliceVariation>;

/**
 * Primary content in *CollapsibleText → Default → Primary*
 */
export interface CollapsibleTextSliceDefaultPrimary {
    /**
     * Title field in *CollapsibleText → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Text field in *CollapsibleText → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.default.primary.text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField;

    /**
     * Accent field in *CollapsibleText → Default → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.default.primary.accent
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    accent: prismic.ColorField;

    /**
     * Accent Dark field in *CollapsibleText → Default → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: collapsible_text.default.primary.accent_dark
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    accent_dark: prismic.ColorField;
}

/**
 * Default variation for CollapsibleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapsibleTextSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CollapsibleTextSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *CollapsibleText*
 */
type CollapsibleTextSliceVariation = CollapsibleTextSliceDefault;

/**
 * CollapsibleText Shared Slice
 *
 * - **API ID**: `collapsible_text`
 * - **Description**: CollapsibleText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapsibleTextSlice = prismic.SharedSlice<'collapsible_text', CollapsibleTextSliceVariation>;

/**
 * Primary content in *Collection → Default → Primary*
 */
export interface CollectionSliceDefaultPrimary {
    /**
     * Handle field in *Collection → Default → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.default.primary.handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;

    /**
     * Title field in *Collection → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Body field in *Collection → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.default.primary.body
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    body: prismic.RichTextField;

    /**
     * Alignment field in *Collection → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: left
     * - **API ID Path**: collection.default.primary.alignment
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    alignment: prismic.SelectField<'left' | 'center' | 'right', 'filled'>;

    /**
     * Item Limit field in *Collection → Default → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 16
     * - **API ID Path**: collection.default.primary.limit
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    limit: prismic.NumberField;

    /**
     * Direction field in *Collection → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: horizontal
     * - **API ID Path**: collection.default.primary.direction
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    direction: prismic.SelectField<'horizontal' | 'grid', 'filled'>;

    /**
     * View All Card field in *Collection → Default → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: collection.default.primary.show_view_all_card
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    show_view_all_card: prismic.BooleanField;

    /**
     * Display field in *Collection → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: in-container
     * - **API ID Path**: collection.default.primary.display
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    display: prismic.SelectField<'in-container' | 'full-width', 'filled'>;
}

/**
 * Default variation for Collection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<CollectionSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Collection*
 */
type CollectionSliceVariation = CollectionSliceDefault;

/**
 * Collection Shared Slice
 *
 * - **API ID**: `collection`
 * - **Description**: Collection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionSlice = prismic.SharedSlice<'collection', CollectionSliceVariation>;

/**
 * Primary content in *IconGrid → Items*
 */
export interface IconGridSliceDefaultItem {
    /**
     * Icon field in *IconGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_grid.items[].icon
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    icon: prismic.ImageField<never>;

    /**
     * Title field in *IconGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Default variation for IconGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<IconGridSliceDefaultItem>
>;

/**
 * Slice variation for *IconGrid*
 */
type IconGridSliceVariation = IconGridSliceDefault;

/**
 * IconGrid Shared Slice
 *
 * - **API ID**: `icon_grid`
 * - **Description**: IconGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconGridSlice = prismic.SharedSlice<'icon_grid', IconGridSliceVariation>;

/**
 * Primary content in *ImageGrid → Items*
 */
export interface ImageGridSliceDefaultItem {
    /**
     * Image field in *ImageGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Title field in *ImageGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * href field in *ImageGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_grid.items[].href
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    href: prismic.KeyTextField;
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ImageGridSliceDefaultItem>
>;

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridSliceVariation = ImageGridSliceDefault;

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: ImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSlice = prismic.SharedSlice<'image_grid', ImageGridSliceVariation>;

/**
 * Normal variation for Spacing Slice
 *
 * - **API ID**: `normal`
 * - **Description**: Normal
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacingSliceNormal = prismic.SharedSliceVariation<'normal', Record<string, never>, never>;

/**
 * Large variation for Spacing Slice
 *
 * - **API ID**: `large`
 * - **Description**: Normal
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacingSliceLarge = prismic.SharedSliceVariation<'large', Record<string, never>, never>;

/**
 * Small variation for Spacing Slice
 *
 * - **API ID**: `small`
 * - **Description**: Normal
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacingSliceSmall = prismic.SharedSliceVariation<'small', Record<string, never>, never>;

/**
 * Primary content in *Spacing → Custom → Primary*
 */
export interface SpacingSliceCustomPrimary {
    /**
     * Scaling field in *Spacing → Custom → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: spacing.custom.primary.scaling
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    scaling: prismic.NumberField;
}

/**
 * Custom variation for Spacing Slice
 *
 * - **API ID**: `custom`
 * - **Description**: Normal
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacingSliceCustom = prismic.SharedSliceVariation<'custom', Simplify<SpacingSliceCustomPrimary>, never>;

/**
 * Slice variation for *Spacing*
 */
type SpacingSliceVariation = SpacingSliceNormal | SpacingSliceLarge | SpacingSliceSmall | SpacingSliceCustom;

/**
 * Spacing Shared Slice
 *
 * - **API ID**: `spacing`
 * - **Description**: Spacing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacingSlice = prismic.SharedSlice<'spacing', SpacingSliceVariation>;

/**
 * Primary content in *Overview → Items*
 */
export interface TextBlockSliceDefaultItem {
    /**
     * Layout field in *Overview → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Image on the left or the right?
     * - **Default Value**: left
     * - **API ID Path**: text_block.items[].layout
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    layout: prismic.SelectField<'left' | 'right' | 'center', 'filled'>;

    /**
     * Accent field in *Overview → Items*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.items[].accent
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    accent: prismic.ColorField;

    /**
     * Image field in *Overview → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Image Style field in *Overview → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: normal
     * - **API ID Path**: text_block.items[].image_style
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    image_style: prismic.SelectField<'normal' | 'cover', 'filled'>;

    /**
     * Text field in *Overview → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Content
     * - **API ID Path**: text_block.items[].text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField;
}

/**
 * Default variation for Overview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image on the left side
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<TextBlockSliceDefaultItem>
>;

/**
 * Slice variation for *Overview*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * Overview Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: An image with a textblock to the side of it
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<'text_block', TextBlockSliceVariation>;

/**
 * Primary content in *Title → Default → Primary*
 */
export interface TitleSliceDefaultPrimary {
    /**
     * Content field in *Title → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title.default.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;

    /**
     * Alignment field in *Title → Default → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: left
     * - **API ID Path**: title.default.primary.alignment
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    alignment: prismic.SelectField<'left' | 'center' | 'right', 'filled'>;
}

/**
 * Default variation for Title Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSliceDefault = prismic.SharedSliceVariation<'default', Simplify<TitleSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Title*
 */
type TitleSliceVariation = TitleSliceDefault;

/**
 * Title Shared Slice
 *
 * - **API ID**: `title`
 * - **Description**: Title
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSlice = prismic.SharedSlice<'title', TitleSliceVariation>;

/**
 * Default variation for Vendors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VendorsSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *Vendors*
 */
type VendorsSliceVariation = VendorsSliceDefault;

/**
 * Vendors Shared Slice
 *
 * - **API ID**: `vendors`
 * - **Description**: Vendors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VendorsSlice = prismic.SharedSlice<'vendors', VendorsSliceVariation>;

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
    /**
     * Title field in *NavigationItem → Default → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The title/name of the link
     * - **API ID Path**: navigation_item.default.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Link field in *NavigationItem → Default → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: The target link
     * - **API ID Path**: navigation_item.default.primary.link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField;

    /**
     * Child Menu field in *NavigationItem → Default → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.default.primary.child_menu
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    child_menu: prismic.ContentRelationshipField<'menu_item'>;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<NavigationItemSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<'navigation_item', NavigationItemSliceVariation>;

/**
 * Default variation for Description Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDescriptionSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *Description*
 */
type ProductDescriptionSliceVariation = ProductDescriptionSliceDefault;

/**
 * Description Shared Slice
 *
 * - **API ID**: `product_description`
 * - **Description**: A component that automatically renders the description of the current product
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDescriptionSlice = prismic.SharedSlice<'product_description', ProductDescriptionSliceVariation>;

declare module '@prismicio/client' {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            ArticlePageDocument,
            ArticlePageDocumentData,
            ArticlePageDocumentDataSlicesSlice,
            CollectionPageDocument,
            CollectionPageDocumentData,
            CollectionPageDocumentDataSlicesSlice,
            CustomPageDocument,
            CustomPageDocumentData,
            CustomPageDocumentDataSlicesSlice,
            FooterDocument,
            FooterDocumentData,
            FooterDocumentDataBodyBlockSlicePrimary,
            FooterDocumentDataBodyBlockSliceItem,
            FooterDocumentDataBodySlice,
            HeadDocument,
            HeadDocumentData,
            HeadDocumentDataAnnouncementsItem,
            HeadDocumentDataNavigationItem,
            MenuItemDocument,
            MenuItemDocumentData,
            MenuItemDocumentDataSlicesSlice,
            NavigationDocument,
            NavigationDocumentData,
            NavigationDocumentDataBodyLinkSlicePrimary,
            NavigationDocumentDataBodyLinkSliceItem,
            NavigationDocumentDataBodySlice,
            ProductPageDocument,
            ProductPageDocumentData,
            ProductPageDocumentDataSlicesSlice,
            ProductPageDocumentDataSlices2Slice,
            StoreDocument,
            StoreDocumentData,
            StoreDocumentDataCurrenciesItem,
            AllDocumentTypes,
            AlertSlice,
            AlertSliceDefaultPrimary,
            AlertSliceVariation,
            AlertSliceDefault,
            BannerSlice,
            BannerSliceDefaultPrimary,
            BannerSliceDefaultItem,
            BannerSliceSimpleSlimPrimary,
            BannerSliceSimpleSlimItem,
            BannerSliceVariation,
            BannerSliceDefault,
            BannerSliceSimpleSlim,
            CarouselSlice,
            CarouselSliceDefaultPrimary,
            CarouselSliceDefaultItem,
            CarouselSliceVariation,
            CarouselSliceDefault,
            CollapsibleTextSlice,
            CollapsibleTextSliceDefaultPrimary,
            CollapsibleTextSliceVariation,
            CollapsibleTextSliceDefault,
            CollectionSlice,
            CollectionSliceDefaultPrimary,
            CollectionSliceVariation,
            CollectionSliceDefault,
            IconGridSlice,
            IconGridSliceDefaultItem,
            IconGridSliceVariation,
            IconGridSliceDefault,
            ImageGridSlice,
            ImageGridSliceDefaultItem,
            ImageGridSliceVariation,
            ImageGridSliceDefault,
            SpacingSlice,
            SpacingSliceCustomPrimary,
            SpacingSliceVariation,
            SpacingSliceNormal,
            SpacingSliceLarge,
            SpacingSliceSmall,
            SpacingSliceCustom,
            TextBlockSlice,
            TextBlockSliceDefaultItem,
            TextBlockSliceVariation,
            TextBlockSliceDefault,
            TitleSlice,
            TitleSliceDefaultPrimary,
            TitleSliceVariation,
            TitleSliceDefault,
            VendorsSlice,
            VendorsSliceVariation,
            VendorsSliceDefault,
            NavigationItemSlice,
            NavigationItemSliceDefaultPrimary,
            NavigationItemSliceVariation,
            NavigationItemSliceDefault,
            ProductDescriptionSlice,
            ProductDescriptionSliceVariation,
            ProductDescriptionSliceDefault
        };
    }
}
