/**
 * Descriptor-driven generator for the Convex CMS localized-paths registry
 * (G4FIX-02).
 *
 * Walks the editor collection schemas (`editorCollectionSchema`) — the same
 * descriptor trees the native form renders and writes buckets from — and emits
 * `packages/convex/convex/cms/localized_paths.ts`: the per-collection set of
 * `localized: true` field paths (array/blocks indices wildcarded to `*`) plus
 * the registered locale-code universe from `config/locale-codes`. The Convex
 * isolate cannot import `@nordcom/commerce-cms` (its config modules read
 * `process.env` at load), so the read seam's bucket detection consumes this
 * generated mirror instead — schema-driven, never shape-guessed, with the
 * `cms:gen:check` drift gate keeping it in lockstep with the descriptors.
 */
import { REGISTERED_LOCALE_CODES } from '../../src/config/locale-codes';
import { editorCollectionSchema } from '../../src/editor/collection-fields';
import { allManifests } from '../../src/editor/manifests';

/** Structural view of a field descriptor as walked by the emitter. */
type WalkField = {
    type: string;
    name?: string;
    localized?: boolean;
    fields?: WalkField[];
    blocks?: Array<{ slug: string; fields: WalkField[] }>;
};

/**
 * Collects the localized path patterns of one descriptor tree into `out`.
 * A `localized: true` descriptor contributes its own path and is NOT recursed:
 * the whole stored value at that path is the bucket (its children live inside
 * a locale slot, mirroring Payload's localized-group storage). Array and
 * blocks rows contribute a `*` wildcard segment; block variants sharing a leaf
 * name union into one pattern — acceptable because the value-level
 * registered-locale check still guards collapsing.
 *
 * @param fields - The descriptor list to walk.
 * @param prefix - The dotted/wildcarded path accumulated so far (empty at the root).
 * @param out - The pattern accumulator.
 */
const collectLocalizedPatterns = (fields: readonly WalkField[], prefix: string, out: Set<string>): void => {
    for (const field of fields) {
        if (field.type === 'collapsible') {
            collectLocalizedPatterns(field.fields ?? [], prefix, out);
            continue;
        }
        if (field.name === undefined) continue;
        const path = prefix === '' ? field.name : `${prefix}.${field.name}`;
        if (field.localized === true) {
            out.add(path);
            continue;
        }
        if (field.type === 'group') {
            collectLocalizedPatterns(field.fields ?? [], path, out);
        } else if (field.type === 'array') {
            collectLocalizedPatterns(field.fields ?? [], `${path}.*`, out);
        } else if (field.type === 'blocks') {
            for (const block of field.blocks ?? []) {
                collectLocalizedPatterns(block.fields ?? [], `${path}.*`, out);
            }
        }
    }
};

/**
 * Resolves the sorted localized path patterns for one collection slug.
 *
 * @param slug - The collection slug.
 * @returns The collection's localized path patterns, sorted for stable output.
 */
export const localizedPatternsFor = (slug: string): string[] => {
    const out = new Set<string>();
    collectLocalizedPatterns(editorCollectionSchema(slug).fields as WalkField[], '', out);
    return [...out].sort();
};

const HEADER = `// AUTO-GENERATED by \`pnpm cms:gen\`. Do not edit by hand — changes will be
// overwritten the next time the generator runs. Edit the descriptor schemas
// that drive this file at packages/cms/src/editor/collection-fields.ts (and
// the locale universe at packages/cms/src/config/locale-codes.ts).
`;

/**
 * Renders a string-array literal, one quoted entry per line at the given indent.
 *
 * @param values - The entries to render.
 * @param indent - Indentation prefix for each entry line.
 * @returns The rendered entry lines (empty string for no entries).
 */
const renderEntries = (values: readonly string[], indent: string): string =>
    values.map((value) => `${indent}'${value}',`).join('\n');

/**
 * Renders the complete `convex/cms/localized_paths.ts` source from the editor
 * collection schemas and the registered locale-code universe.
 *
 * @returns The full file contents, newline-terminated.
 */
export const generateConvexLocalizedPaths = (): string => {
    const slugs = [...new Set(allManifests.map((manifest) => String(manifest.collection)))].sort();
    const collections = slugs
        .map((slug) => {
            const patterns = localizedPatternsFor(slug);
            const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(slug) ? slug : `'${slug}'`;
            if (patterns.length === 0) return `    ${key}: [],`;
            return `    ${key}: [\n${renderEntries(patterns, '        ')}\n    ],`;
        })
        .join('\n');
    const codes = renderEntries([...REGISTERED_LOCALE_CODES].sort(), '    ');

    return `${HEADER}
/**
 * The registered locale-code universe (\`config/locale-codes.ts\`'s ISO 639-1 +
 * curated BCP-47 supersets). A bare bucket key must be a member; region-tagged
 * keys are additionally accepted by grammar (\`xx-XX\`) in
 * \`localization.ts\`'s \`isLocaleBucket\`.
 */
// biome-ignore format: generated output must stay byte-stable under the cms:gen drift gate
export const CMS_REGISTERED_LOCALE_CODES: readonly string[] = [
${codes}
];

/**
 * Per-collection localized field paths derived from the editor descriptor
 * schemas (\`localized: true\`), with array/blocks indices wildcarded to \`*\`.
 * A path names where a per-field locale bucket may legally sit; everywhere
 * else the read seam passes values through untouched (G4FIX-02). A localized
 * container (group/array) contributes ONE path — its whole value is the
 * bucket.
 */
// biome-ignore format: generated output must stay byte-stable under the cms:gen drift gate
export const CMS_LOCALIZED_PATHS_BY_COLLECTION: Record<string, readonly string[]> = {
${collections}
};
`;
};
