/**
 * Single source of truth for every file `pnpm cms:gen` generates from the CMS
 * descriptors and editor manifests. Both the writer (`scripts/cms-gen.ts`) and
 * the drift gate (`scripts/cms-gen-check.ts`) consume {@link collectGeneratedOutputs}
 * so they can never diverge on what's generated or where it lands.
 *
 * Four artifact families, all descriptor/manifest-driven and free of any
 * Payload runtime or Mongo adapter:
 *   1. admin editor-action wrappers (one per editor manifest);
 *   2. `packages/cms/src/types/payload-types.ts` (the storefront read-contract types);
 *   3. `packages/convex/convex/tables/cms.ts` (the CMS content-table validators);
 *   4. `packages/convex/convex/cms/localized_paths.ts` (the schema-driven
 *      localized-path + locale-code registry the read seam's bucket detection
 *      consumes — G4FIX-02).
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateConvexCmsTables } from './emit-convex-tables';
import { generateConvexLocalizedPaths } from './emit-localized-paths';
import { generatePayloadTypes } from './emit-payload-types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../../..');
const CMS_ROOT = path.resolve(__dirname, '../..');
const EDITOR_ACTIONS_DIR = path.join(REPO_ROOT, 'apps/admin/src/lib/cms-actions/_generated');

/** A single generated file: its absolute path and full intended contents. */
export type GeneratedOutput = { path: string; content: string };

const EDITOR_WRAPPER_HEADER = `// AUTO-GENERATED by \`pnpm cms:gen\`. Do not edit by hand — changes will be
// overwritten the next time the generator runs. Edit the manifest that drives
// this file at packages/cms/src/editor/manifests/.
`;

/**
 * Capitalizes the first character of a string.
 *
 * @param value - The string to capitalize.
 * @returns `value` with its first character upper-cased.
 */
const capitalize = (value: string): string =>
    value.length === 0 ? value : value.charAt(0).toUpperCase() + value.slice(1);

/**
 * Converts a kebab-case slug to camelCase.
 *
 * @param slug - The slug to convert.
 * @returns The camelCased form.
 */
const slugToCamel = (slug: string): string => slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

/**
 * Renders the admin editor-action wrapper module for one collection editor.
 * Re-exports the seven `EditorActions` methods as top-level `'use server'`
 * functions so Next.js can encode them as transferable action IDs.
 *
 * @param input - The collection slug and the manifest import name.
 * @returns The full TypeScript source for the wrapper module.
 */
export const generateActionWrapper = (input: { slug: string; importName: string }): string => {
    const { slug, importName } = input;
    const camel = slugToCamel(slug);
    const fn = (method: string): string => `${camel}${capitalize(method)}`;
    return `${EDITOR_WRAPPER_HEADER}'use server';

import 'server-only';

import { createCollectionEditorActions } from '@nordcom/commerce-cms/editor';
import { ${importName} } from '@nordcom/commerce-cms/editor/manifests';

import { editorRuntime } from '@/lib/editor-runtime';

const a = createCollectionEditorActions(${importName}, editorRuntime);

// Signatures are written multi-line so Biome's auto-format hook leaves them
// alone regardless of slug length. Short slugs (pages) and long slugs
// (collectionMetadata) all emit the same shape, keeping cms:gen:check
// deterministic. Do NOT use backticks in comments inside this template
// literal — they would collide with the outer string delimiter.
export async function ${fn('saveDraft')}(
    domain: string | null,
    id: string,
    formData: FormData,
    locale: string,
): Promise<void> {
    return a.saveDraft(domain, id, formData, locale);
}
export async function ${fn('publish')}(
    domain: string | null,
    id: string,
    formData: FormData,
    locale: string,
): Promise<void> {
    return a.publish(domain, id, formData, locale);
}
export async function ${fn('create')}(
    domain: string | null,
    formData: FormData,
    locale: string,
): Promise<{ id: string }> {
    return a.create(domain, formData, locale);
}
export async function ${fn('delete')}(
    domain: string | null,
    id: string,
): Promise<void> {
    return a.delete(domain, id);
}
export async function ${fn('bulkDelete')}(
    domain: string | null,
    ids: string[],
): Promise<void> {
    return a.bulkDelete(domain, ids);
}
export async function ${fn('bulkPublish')}(
    domain: string | null,
    ids: string[],
): Promise<void> {
    return a.bulkPublish(domain, ids);
}
export async function ${fn('restoreVersion')}(
    domain: string | null,
    id: string,
    versionId: string,
): Promise<void> {
    return a.restoreVersion(domain, id, versionId);
}
`;
};

/**
 * Collects every file `pnpm cms:gen` should produce, in a stable order. Pure
 * descriptor/manifest computation — performs no file I/O and boots no Payload.
 *
 * @returns The full set of generated outputs (path + content).
 */
export const collectGeneratedOutputs = async (): Promise<GeneratedOutput[]> => {
    const { allManifests } = await import('../../src/editor/manifests/index.js');

    const outputs: GeneratedOutput[] = [];

    for (const manifest of allManifests) {
        const slug = String(manifest.collection);
        const importName = `${slugToCamel(slug)}Editor`;
        outputs.push({
            path: path.join(EDITOR_ACTIONS_DIR, `${slug}.ts`),
            content: generateActionWrapper({ slug, importName }),
        });
    }

    outputs.push({
        path: path.join(CMS_ROOT, 'src/types/payload-types.ts'),
        content: generatePayloadTypes(),
    });

    outputs.push({
        path: path.join(REPO_ROOT, 'packages/convex/convex/tables/cms.ts'),
        content: generateConvexCmsTables(),
    });

    outputs.push({
        path: path.join(REPO_ROOT, 'packages/convex/convex/cms/localized_paths.ts'),
        content: generateConvexLocalizedPaths(),
    });

    return outputs;
};
