// AUTO-GENERATED by `pnpm cms:gen`. Do not edit by hand — changes will be
// overwritten the next time the generator runs. Edit the manifest that drives
// this file at packages/cms/src/editor/manifests/.
'use server';

import 'server-only';

import { createCollectionEditorActions } from '@nordcom/commerce-cms/editor';
import { collectionMetadataEditor } from '@nordcom/commerce-cms/editor/manifests';

import { editorRuntime } from '@/lib/editor-runtime';

const a = createCollectionEditorActions(collectionMetadataEditor, editorRuntime);

export async function collectionMetadataSaveDraft(
    domain: string | null,
    id: string,
    formData: FormData,
): Promise<void> {
    return a.saveDraft(domain, id, formData);
}
export async function collectionMetadataPublish(domain: string | null, id: string, formData: FormData): Promise<void> {
    return a.publish(domain, id, formData);
}
export async function collectionMetadataCreate(domain: string | null, formData: FormData): Promise<{ id: string }> {
    return a.create(domain, formData);
}
export async function collectionMetadataDelete(domain: string | null, id: string): Promise<void> {
    return a.delete(domain, id);
}
export async function collectionMetadataBulkDelete(domain: string | null, ids: string[]): Promise<void> {
    return a.bulkDelete(domain, ids);
}
export async function collectionMetadataBulkPublish(domain: string | null, ids: string[]): Promise<void> {
    return a.bulkPublish(domain, ids);
}
export async function collectionMetadataRestoreVersion(
    domain: string | null,
    id: string,
    versionId: string,
): Promise<void> {
    return a.restoreVersion(domain, id, versionId);
}
