// AUTO-GENERATED by `pnpm cms:gen`. Do not edit by hand — changes will be
// overwritten the next time the generator runs. Edit the manifest that drives
// this file at packages/cms/src/editor/manifests/.
'use server';

import 'server-only';

import { createCollectionEditorActions } from '@nordcom/commerce-cms/editor';
import { featureFlagsEditor } from '@nordcom/commerce-cms/editor/manifests';

import { editorRuntime } from '@/lib/editor-runtime';

const a = createCollectionEditorActions(featureFlagsEditor, editorRuntime);

export async function featureFlagsSaveDraft(domain: string | null, id: string, formData: FormData): Promise<void> {
    return a.saveDraft(domain, id, formData);
}
export async function featureFlagsPublish(domain: string | null, id: string, formData: FormData): Promise<void> {
    return a.publish(domain, id, formData);
}
export async function featureFlagsCreate(domain: string | null, formData: FormData): Promise<{ id: string }> {
    return a.create(domain, formData);
}
export async function featureFlagsDelete(domain: string | null, id: string): Promise<void> {
    return a.delete(domain, id);
}
export async function featureFlagsBulkDelete(domain: string | null, ids: string[]): Promise<void> {
    return a.bulkDelete(domain, ids);
}
export async function featureFlagsBulkPublish(domain: string | null, ids: string[]): Promise<void> {
    return a.bulkPublish(domain, ids);
}
export async function featureFlagsRestoreVersion(domain: string | null, id: string, versionId: string): Promise<void> {
    return a.restoreVersion(domain, id, versionId);
}
