// AUTO-GENERATED by `pnpm cms:gen`. Do not edit by hand — changes will be
// overwritten the next time the generator runs. Edit the manifest that drives
// this file at packages/cms/src/editor/manifests/.
'use server';

import 'server-only';

import { createCollectionEditorActions } from '@nordcom/commerce-cms/editor';
import { pagesEditor } from '@nordcom/commerce-cms/editor/manifests';

import { editorRuntime } from '@/lib/editor-runtime';

const a = createCollectionEditorActions(pagesEditor, editorRuntime);

// Signatures are written multi-line so Biome's auto-format hook leaves them
// alone regardless of slug length. Short slugs (pages) and long slugs
// (collectionMetadata) all emit the same shape, keeping cms:gen:check
// deterministic. Do NOT use backticks in comments inside this template
// literal — they would collide with the outer string delimiter.
export async function pagesSaveDraft(
    domain: string | null,
    id: string,
    formData: FormData,
    locale: string,
): Promise<void> {
    return a.saveDraft(domain, id, formData, locale);
}
export async function pagesPublish(
    domain: string | null,
    id: string,
    formData: FormData,
    locale: string,
): Promise<void> {
    return a.publish(domain, id, formData, locale);
}
export async function pagesCreate(
    domain: string | null,
    formData: FormData,
    locale: string,
): Promise<{ id: string }> {
    return a.create(domain, formData, locale);
}
export async function pagesDelete(
    domain: string | null,
    id: string,
): Promise<void> {
    return a.delete(domain, id);
}
export async function pagesBulkDelete(
    domain: string | null,
    ids: string[],
): Promise<void> {
    return a.bulkDelete(domain, ids);
}
export async function pagesBulkPublish(
    domain: string | null,
    ids: string[],
): Promise<void> {
    return a.bulkPublish(domain, ids);
}
export async function pagesRestoreVersion(
    domain: string | null,
    id: string,
    versionId: string,
): Promise<void> {
    return a.restoreVersion(domain, id, versionId);
}
